# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//930-ng-core-clients/src/main/java/io/harness/organization/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/project/remote:module",
        "//940-feature-flag/src/main/java/io/harness/ff:module",
        "//955-account-mgmt/src/main/java/io/harness/account/utils:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//958-migration-sdk/src/main/java/io/harness/migration/beans:module",
        "//958-migration-sdk/src/main/java/io/harness/migration/entities:module",
        "//958-migration-sdk/src/main/java/io/harness/migration/ng:module",
        "//958-migration-sdk/src/main/java/io/harness/migration/postgres:module",
        "//958-migration-sdk/src/main/java/io/harness/migration/timescale:module",
        "//959-ng-persistence/src/main/java/io/harness/cache:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-persistence/src/main/java/io/harness/elasticsearch:module",
        "//960-persistence/src/main/java/io/harness/elasticsearch/utils:module",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//960-persistence/src/main/java/io/harness/mongo:module",
        "//960-persistence/src/main/java/io/harness/ng:module",
        "//960-persistence/src/main/java/io/harness/objectstore:module",
        "//960-persistence/src/main/java/io/harness/objectstore/beans:module",
        "//960-persistence/src/main/java/io/harness/postgres:module",
        "//960-persistence/src/main/java/io/harness/timescaledb:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//980-commons/src/main/java/io/harness/annotations:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api:module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol:module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol/migration:module",
        "//clients/resource-group/src/main/java/io/harness/resourcegroupclient/remote:module",
        "//pipeline-service/modules/migrations/src/java/io/harness/projectmovement/mongo:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/config:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/artifact:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/bitbucket/event:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/github/event:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/spec:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/gitmetadata:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution/gitmetadata/beans:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/sdk:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities:module",
        "//pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/repositories/executions:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/gitmetadata/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/accountoverrides:module",
        "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/dataretention/entity:module",
        "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/reconciliation/entity:module",
        "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/reconciliation/entity/beans:module",
        "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/search/entity/beans:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/dataretention/jobs/service:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/dataretention/utils:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/reconciliation/service:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/search/service:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/search/utils:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/utils:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/migration/background:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline:module",
        "//resource-group-service/contracts/src/main/java/io/harness/resourcegroup/v1/remote/dto:module",
        "//resource-group-service/contracts/src/main/java/io/harness/resourcegroup/v2/model:module",
        "//resource-group-service/contracts/src/main/java/io/harness/resourcegroup/v2/remote/dto:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:io_dropwizard_dropwizard_lifecycle",
        "@maven//:javax_annotation_javax_annotation_api",
        "@maven//:javax_cache_cache_api",
        "@maven//:net_jodah_failsafe",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_hibernate_validator_hibernate_validator",
        "@maven//:org_mongodb_mongo_java_driver",
        "@maven//:org_mybatis_mybatis",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
