# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/common/helper:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/dto:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/helper:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitx:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/entityInfo:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/helpers:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans:module",
        "//930-ng-core-clients/src/main/java/io/harness/organization/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/project/remote:module",
        "//952-scm-java-client/src/main/java/io/harness/exception:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//953-git-sync-commons/src/main/java/io/harness/gitsync/common/utils:module",
        "//953-git-sync-commons/src/main/java/io/harness/gitsync/interceptor:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/gitsync:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml/validator:module",
        "//970-api-services-beans/src/main/java/io/harness/git/model:module",
        "//970-grpc/src/main/java/io/harness/grpc/utils:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/common:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/beans:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/interceptor:module",
        "//970-ng-commons/src/main/java/io/harness/gitx:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils:module",
        "//970-ng-commons/src/main/java/io/harness/yaml/validator/beans:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception/beans/yamlschema:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/utils:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/ngpipeline/inputset/beans/resource:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset/gitsync/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/instrumentaion:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/instrumentaion/constants:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/utils:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/validate:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/setupusage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/response:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/inputset:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/pipeline:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:commons_collections_commons_collections",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_tx",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
