# Copyright 2026 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//:__subpackages__"],
    deps = [
        "//:lombok",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/driftdetection/entity:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/driftdetection/expression:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/driftdetection/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/repositories/driftdetection:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/driftdetection:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/listener:module",
        "//910-delegate-service-driver/src/main/java/io/harness/beans:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//950-delegate-task-sdk/java/io/harness/task/response/callback:module",
        "//950-delegate-task-sdk/java/io/harness/task/response/grpc:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/k8s:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//951-delegate-task-commons/src/main/java/io/harness/delegate/beans:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//970-api-services-beans/src/main/java/io/harness/logging:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/tasks:module",
        "//980-commons/src/main/java/io/harness/utils:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_inject_guice",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
