pipeline:
  stages:
    - name: ${stageName}
      id: ${stageId}
      service:
        type: kubernetes
        items:
          - ${serviceIdentifier}
      environment:
        id: ${environmentIdentifier}
        deploy-to: ${infrastructureIdentifier}
      steps:
        - name: Kubernetes Canary Deploy
          id: k8sCanaryDeployStep
          template:
            uses: k8sCanaryDeployStep
        - name: Kubernetes Canary Delete
          id: k8sCanaryDeleteStep
          template:
            uses: k8sCanaryDeleteStep
            with:
              resources: <+stage.steps.k8sCanaryDeployStep.output.outputVariables.canaryWorkloads>
              is_openshift: <+stage.steps.k8sCanaryDeployStep.output.outputVariables.isOpenshift>
        - name: Kubernetes Rolling Deploy
          id: k8sRollingDeployStep
          template:
            uses: k8sRollingDeployStep
      rollback:
        - group:
            steps:
              - name: Kubernetes Canary Rollback Delete
                id: k8sCanaryRollbackDeleteStep
                template:
                  uses: k8sCanaryDeleteStep
                  with:
                    select_delete_resources: resources
                    resources: ${{rollback.data.PLUGIN_CANARY_WORKLOADS}}
                    is_openshift: ${{rollback.data.HARNESS_IS_OPENSHIFT}}
              - name: Kubernetes Rolling Rollback
                id: k8sRollingRollbackStep
                template:
                  uses: k8sRollingRollbackStep
      on-failure:
        errors: all
        action: stage-rollback
      runtime: cloud
