# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/utils:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/exceptions:module",
        "//950-opa-client/src/main/java/io/harness/opaclient/model:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/advisers/manualIntervention:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/engine/pms/data:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/steps/io:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/pms/data/stepparameters:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/common/dependencyUtils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/settings/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executioncheck:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/factory:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/outcome:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/modifier/ambiance:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/helper/intfc:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/start:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/metrics:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_intellij_annotations",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
