# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_for_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    resources = [
        "//120-ng-manager/src/test/resources:resource",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/test/java/io/harness/base:tests",
        "//980-commons/src/main/java/io/harness/testing:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "@maven//:com_google_inject_guice",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
    ],
)

run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

java_test(
    name = "NgManagerComponentTest",
    srcs = ["NgManagerComponentTest.java"],
    resources = [
        "//120-ng-manager/src/test/resources:resource",
    ],
    tags = ["component_test"],
    test_class = "io.harness.component.NgManagerComponentTest",
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/test/java/io/harness/base:tests",
        "//980-commons/src/main/java/io/harness/testing:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "@maven//:com_google_inject_guice",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
    ],
)
