# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//323-sto-utilities/src/main/java/io/harness/qwietserviceclient:module",
        "//323-sto-utilities/src/main/java/io/harness/stoserviceclient:module",
        "//332-ssca/commons/src/main/java/io/harness/ssca/client:module",
        "//867-polling-contracts/src/main/java/io/harness/polling/client:module",
        "//874-orchestration-delay/src/main/java/io/harness/delay:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/agent/convert:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/agent/expansion:module",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/opa/gitx:module",
        "//878-ng-common-utilities/src/main/java/io/harness/secretusage:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps/workloadidentity:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/platform/V1:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff/impl:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/metrics:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/permission:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events/base:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/events:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/testing:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/sdk:module",
        "//910-delegate-service-driver/src/main/java/io/harness/client:module",
        "//910-delegate-service-driver/src/main/java/io/harness/grpc:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service/impl:module",
        "//920-delegate-service-beans/src/main/java/io/harness/delegate/beans:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//930-ng-core-clients/src/main/java/io/harness/aisre:module",
        "//930-ng-core-clients/src/main/java/io/harness/cdstage:module",
        "//930-ng-core-clients/src/main/java/io/harness/connector:module",
        "//930-ng-core-clients/src/main/java/io/harness/entitysetupusageclient:module",
        "//930-ng-core-clients/src/main/java/io/harness/environment:module",
        "//930-ng-core-clients/src/main/java/io/harness/filestore:module",
        "//930-ng-core-clients/src/main/java/io/harness/oidc:module",
        "//930-ng-core-clients/src/main/java/io/harness/organization:module",
        "//930-ng-core-clients/src/main/java/io/harness/project:module",
        "//930-ng-core-clients/src/main/java/io/harness/runner/plugin:module",
        "//930-ng-core-clients/src/main/java/io/harness/secrets:module",
        "//930-ng-core-clients/src/main/java/io/harness/serviceaccount:module",
        "//930-ng-core-clients/src/main/java/io/harness/user:module",
        "//930-ng-core-clients/src/main/java/io/harness/usergroups:module",
        "//930-ng-core-clients/src/main/java/io/harness/userng:module",
        "//930-ng-core-clients/src/main/java/io/harness/webhook:module",
        "//937-persistence-tracer/src/main/java/io/harness/tracing:module",
        "//940-feature-flag/src/main/java/io/harness/ff:module",
        "//940-primary-version-manager/src/main/java/io/harness/app:module",
        "//940-primary-version-manager/src/main/java/io/harness/controller:module",
        "//940-primary-version-manager/src/main/java/io/harness/resource:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/custom:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/resources:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/servicedependencies:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/services:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/usage:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/constants:module",
        "//950-log-client/src/main/java/io/harness/logstreaming:module",
        "//950-opa-client/src/main/java/io/harness/opaclient:module",
        "//950-telemetry/src/main/java/io/harness/telemetry:module",
        "//950-telemetry/src/main/java/io/harness/telemetry/filter:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//950-wait-engine/src/main/java/io/harness/waiter/nrcsp:module",
        "//950-wait-engine/src/main/java/io/harness/waiter/persistence:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/impl/noop:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/impl/redis:module",
        "//953-events-api/src/main/java/io/harness/ng/core/event:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//953-git-sync-commons/src/main/java/io/harness/gitsync/common:module",
        "//953-yaml-commons/src/main/java/io/harness/allowedvalues:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/core:module",
        "//955-filters-sdk/src/main/java/io/harness/filter:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/mapper:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/task:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/api:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/eventpoll:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/module",
        "//958-migration-sdk/src/main/java/io/harness/migration/ng:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//959-timeout-engine/src/main/java/io/harness/timeout/engine:module",
        "//960-api-services/src/main/java/io/harness/cistatus/service:module",
        "//960-continuous-features/src/main/java/io/harness/cf:module",
        "//960-continuous-features/src/main/java/io/harness/ff:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/remote:module",
        "//960-persistence/src/main/java/io/harness/cache:module",
        "//960-persistence/src/main/java/io/harness/datastructures:module",
        "//960-persistence/src/main/java/io/harness/elasticsearch:module",
        "//960-persistence/src/main/java/io/harness/iterator:module",
        "//960-persistence/src/main/java/io/harness/iterator/interfaces:module",
        "//960-persistence/src/main/java/io/harness/lock:module",
        "//960-persistence/src/main/java/io/harness/mongo:module",
        "//960-persistence/src/main/java/io/harness/mongo/index:module",
        "//960-persistence/src/main/java/io/harness/ng:module",
        "//960-persistence/src/main/java/io/harness/persistence:module",
        "//960-persistence/src/main/java/io/harness/persistence/api:module",
        "//960-persistence/src/main/java/io/harness/persistence/store:module",
        "//960-persistence/src/main/java/io/harness/postgres:module",
        "//960-persistence/src/main/java/io/harness/queue:module",
        "//960-persistence/src/main/java/io/harness/redis:module",
        "//960-persistence/src/main/java/io/harness/timescaledb:module",
        "//960-persistence/src/main/java/io/harness/timescaledb/metrics:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml/schema/beans:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml/schema/client:module",
        "//965-ng-filter/src/main/java/io/harness/security:module",
        "//965-ng-filter/src/main/java/io/harness/token:module",
        "//965-ng-filter/src/main/java/io/harness/token/remote:module",
        "//970-api-services-beans/src/main/java/io/harness/filter:module",
        "//970-ng-commons/src/main/java/io/harness/cd:module",
        "//970-ng-commons/src/main/java/io/harness/filter:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/monitoring:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/entitydetail:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/filter:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/request:module",
        "//970-ng-commons/src/main/java/io/harness/security/annotations:module",
        "//970-ng-commons/src/main/java/io/serializer/mapper:module",
        "//970-telemetry-beans/src/main/java/io/harness/telemetry:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/configuration:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/govern:module",
        "//980-commons/src/main/java/io/harness/health:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/logstreaming:module",
        "//980-commons/src/main/java/io/harness/maintenance:module",
        "//980-commons/src/main/java/io/harness/manage:module",
        "//980-commons/src/main/java/io/harness/metrics:module",
        "//980-commons/src/main/java/io/harness/morphia:module",
        "//980-commons/src/main/java/io/harness/packages:module",
        "//980-commons/src/main/java/io/harness/reflection:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/mesh:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/threading:module",
        "//980-commons/src/main/java/io/harness/time:module",
        "//980-commons/src/main/java/io/harness/version:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/aggregator/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/health:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/permissions/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/preference/api:module",
        "//access-control/contracts/openapi/v1:access-control-server-spec-module",
        "//access-control/contracts/openapi/v1/resourcegroup:resource-group-server-spec-module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol/publicaccess:module",
        "//clients/audit/src/main/java/io/harness/audit/client/remote:module",
        "//clients/ci/src/main/java/io/harness/ci:module",
        "//clients/git-sync-manager/src/main/java/io/harness/gitsync:module",
        "//clients/go-convert/src/main/java/io/harness/goconvert:module",
        "//clients/harnessid/src/main/java/io/harness/harnessid/client:module",
        "//clients/ng-variables/src/main/java/io/harness/variable:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//clients/notification/src/main/java/io/harness/notification/module",
        "//clients/notification/src/main/java/io/harness/notification/notificationclient:module",
        "//clients/notification/src/main/java/io/harness/notification/templates:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/governance:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/serializer:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/configuration:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/facilitators:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/interrupts:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/advise:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/resume:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/start:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/orchestrationevent:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/progress:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/metrics:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/beans:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model:module",
        "//clients/resource-group/src/main/java/io/harness/resourcegroupclient:module",
        "//clients/scope/src/main/java/io/harness/scopeinfoclient:module",
        "//clients/scope/src/main/java/io/harness/scopeinfoclient/remote:module",
        "//clients/template-service/src/main/java/io/harness/template:module",
        "//clients/webhook/src/main/java/io/harness/webhook/remote:module",
        "//kafka-client/src/main/java/io/harness/kafka:module",
        "//license-manager/libs/enforcement/src/main/java/io/harness/licensing/enforcement/client:module",
        "//license-manager/libs/enforcement/src/main/java/io/harness/licensing/enforcement/client/model:module",
        "//pipeline-service/contracts/src/main/java/io/harness/notify:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/approval/resources:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/barriers/resources:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/dashboard:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/dataretention:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/health:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/inputfile:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/ngpipeline/inputset/resources:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/notificationbodyresolution:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/orchestrationgovernor:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution/resources:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/resourceconstraints/resources:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/schema:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/stagequeue/beans:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/wait:module",
        "//pipeline-service/modules/migrations/src/java/io/harness/projectmovement/elastic:module",
        "//pipeline-service/modules/migrations/src/java/io/harness/projectmovement/gcs:module",
        "//pipeline-service/modules/migrations/src/java/io/harness/projectmovement/mongo:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/outbox:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/sdk:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/pipeline:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/event:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/agent:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/plugin:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/event:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/opa/plugin:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/service:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/cleanup:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/cleanup/config:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/consumers/graph:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/deleteGraph:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/event/streams:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/observers:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/pms/plan/execution/service:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service:module",
        "//pipeline-service/modules/orchestration-visualization/src/main/java/io/harness/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/config:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/consumers/flowgovernor:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/gitmetadata/jobs:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/secondary:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/start:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/timeouts:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/event:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/metrics/observers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/waiter:module",
        "//pipeline-service/modules/outbox/src/main/java/io/harness/api:module",
        "//pipeline-service/modules/outbox/src/main/java/io/harness/api/impl:module",
        "//pipeline-service/modules/outbox/src/main/java/io/harness/eventPoll:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/annotations:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/serializer/json:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/cleanup:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/reconciliation/jobs:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/search/jobs:module",
        "//pipeline-service/service/src/main/java/io/harness/config:module",
        "//pipeline-service/service/src/main/java/io/harness/enforcement:module",
        "//pipeline-service/service/src/main/java/io/harness/grpc/server:module",
        "//pipeline-service/service/src/main/java/io/harness/metrics:module",
        "//pipeline-service/service/src/main/java/io/harness/monitoring:module",
        "//pipeline-service/service/src/main/java/io/harness/notify:module",
        "//pipeline-service/service/src/main/java/io/harness/pipeline/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/annotations:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/custom:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/jira:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/notification/stagemetadata:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/servicenow:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/barriers/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/barriers/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion:beans",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/iterator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/mapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/dashboard:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/dataretention:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/bulkReconciliation:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/filter:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/gitNotification:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/handlers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/overviewLandingPage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/overviewLandingPage/kafka:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/preStepCheckObserver:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/systemevents:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/triggerwebhookevent:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/webhookevent:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/expressions:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/health:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset/gitsync:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset/gitsync/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/instrumentaion/handler:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/jira:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/migration:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/mongo:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputs/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputs/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/migration:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/observers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/gitstatus:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/opa/gitx/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/opa/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/orchestrationgovernor:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/outbox:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/agent:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/labels:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/observer/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/resource:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/enforcement:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/response:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlConversion:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/approval:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/cache:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/featureflag:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/pipelinestage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/setupusage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinedelete/jobs:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation/lookup:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation/lookup/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/dryrun/semantic:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/dryrun/semantic/rules:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/mapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/queue:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plugin:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/preflight/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/preflight/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/rbac/validator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/resourcerestraint/reconciliation/job:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/schema:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/sdk:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/servicenow:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/stagequeue/client:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/stagequeue/resource:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/stagequeue/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/statusreconciliation/job:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/tags:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/template/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/scheduled:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/wait:module",
        "//pipeline-service/service/src/main/java/io/harness/registrars:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/conversion:module",
        "//pipeline-service/service/src/main/java/io/harness/serializer:module",
        "//pipeline-service/service/src/main/java/io/harness/serializer/jackson:module",
        "//platform-service/modules/audit-service/contracts/openapi/v1:audit-server-spec-module",
        "//platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit:module",
        "//platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/remote:module",
        "//platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/remote/resources:module",
        "//platform-service/modules/notification-service/src/main/java/io/harness/notification/modules:module",
        "//srm-service/modules/cv-nextgen-service/contracts/api/src/main/java/io/harness/cvng/client:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:io_dropwizard_dropwizard_configuration",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:io_dropwizard_dropwizard_jackson",
        "@maven//:io_dropwizard_dropwizard_jersey",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:io_swagger_core_v3_swagger_jaxrs2",
        "@maven//:jakarta_servlet_jakarta_servlet_api",
        "@maven//:jakarta_ws_rs_jakarta_ws_rs_api",
        "@maven//:javax_cache_cache_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:net_sourceforge_argparse4j_argparse4j",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_codehaus_janino_janino",
        "@maven//:org_eclipse_jetty_jetty_servlets",
        "@maven//:org_glassfish_jersey_media_jersey_media_multipart",
        "@maven//:org_jooq_jooq",
        "@maven//:org_mongodb_mongo_java_driver",
        "@maven//:org_reflections_reflections",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_core",
        "@maven//:org_springframework_spring_tx",
        "@maven_redisson//:org_redisson_redisson",
    ],
)

java_binary(
    name = "PipelineServiceApplication",
    main_class = "io.harness.PipelineServiceApplication",
    visibility = ["//visibility:public"],
    runtime_deps = [":module"],
    deps = [],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
