# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//332-ci-manager/contracts/src/main/java/io/harness/beans/steps/stepinfo:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/dependencies:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/stages/V1:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/execution:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/outcome:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/sweepingoutputs:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/cd/core:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/infrastrucutre:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/platform:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/platform/V1:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/runtime:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/runtime/V1:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/volumes:module",
        "//953-yaml-commons/src/main/java/io/harness/when/beans:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/core/variables/v1:module",
        "//980-commons/src/main/java/io/harness/morphia:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "@maven//:com_esotericsoftware_kryo",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
