/*
 * Copyright 2022 Harness Inc. All rights reserved.
 * Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
 * that can be found in the licenses directory at the root of this repository, also available at
 * https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.
 */

package io.harness.cimanager.serializer;

import static io.harness.beans.yaml.extended.infrastrucutre.VmPoolYaml.VmPoolYamlSpec;
import static io.harness.beans.yaml.extended.volumes.ConfigMapVolumeYaml.ConfigMapVolumeYamlSpec;
import static io.harness.beans.yaml.extended.volumes.EmptyDirYaml.EmptyDirYamlSpec;
import static io.harness.beans.yaml.extended.volumes.HostPathYaml.HostPathYamlSpec;
import static io.harness.beans.yaml.extended.volumes.PersistentVolumeClaimYaml.PersistentVolumeClaimYamlSpec;
import static io.harness.beans.yaml.extended.volumes.SecretVolumeYaml.SecretVolumeYamlSpec;
import static io.harness.beans.yaml.extended.volumes.V1.ConfigMapVolumeYamlV1.ConfigMapVolumeYamlSpecV1;
import static io.harness.beans.yaml.extended.volumes.V1.EmptyDirYamlV1.EmptyDirYamlV1Spec;
import static io.harness.beans.yaml.extended.volumes.V1.HostPathYamlV1.HostPathYamlSpecV1;
import static io.harness.beans.yaml.extended.volumes.V1.PersistentVolumeClaimYamlV1.PersistentVolumeClaimYamlSpecV1;
import static io.harness.beans.yaml.extended.volumes.V1.SecretVolumeYamlV1.SecretVolumeYamlSpecV1;

import io.harness.beans.dependencies.CIServiceInfo;
import io.harness.beans.dependencies.DependencyElement;
import io.harness.beans.execution.PublishedFileArtifact;
import io.harness.beans.execution.PublishedImageArtifact;
import io.harness.beans.steps.outcome.CIStepOutcome;
import io.harness.beans.steps.outcome.StepArtifacts;
import io.harness.beans.steps.stepinfo.CleanupStepInfo;
import io.harness.beans.steps.stepinfo.DockerStepInfo;
import io.harness.beans.steps.stepinfo.ECRStepInfo;
import io.harness.beans.steps.stepinfo.GCRStepInfo;
import io.harness.beans.steps.stepinfo.GitCloneStepInfo;
import io.harness.beans.steps.stepinfo.PluginStepInfo;
import io.harness.beans.steps.stepinfo.RestoreCacheGCSStepInfo;
import io.harness.beans.steps.stepinfo.RestoreCacheS3StepInfo;
import io.harness.beans.steps.stepinfo.RestoreCacheStepInfo;
import io.harness.beans.steps.stepinfo.RunStepInfo;
import io.harness.beans.steps.stepinfo.RunTestStepV2Info;
import io.harness.beans.steps.stepinfo.RunTestsStepInfo;
import io.harness.beans.steps.stepinfo.SaveCacheGCSStepInfo;
import io.harness.beans.steps.stepinfo.SaveCacheS3StepInfo;
import io.harness.beans.steps.stepinfo.SaveCacheStepInfo;
import io.harness.beans.steps.stepinfo.SecurityStepInfo;
import io.harness.beans.steps.stepinfo.TestStepInfo;
import io.harness.beans.steps.stepinfo.UploadToArtifactoryStepInfo;
import io.harness.beans.steps.stepinfo.UploadToGCSStepInfo;
import io.harness.beans.steps.stepinfo.UploadToHarStepInfo;
import io.harness.beans.steps.stepinfo.UploadToS3StepInfo;
import io.harness.beans.sweepingoutputs.StageInfraDetails;
import io.harness.beans.yaml.extended.CIResourceClass;
import io.harness.beans.yaml.extended.CustomSecretVariable;
import io.harness.beans.yaml.extended.CustomTextVariable;
import io.harness.beans.yaml.extended.CustomVariable;
import io.harness.beans.yaml.extended.beans.PullPolicy;
import io.harness.beans.yaml.extended.cd.core.UnifiedEnvironmentYaml;
import io.harness.beans.yaml.extended.infrastrucutre.DockerInfraYaml;
import io.harness.beans.yaml.extended.infrastrucutre.DockerInfraYaml.DockerInfraSpec;
import io.harness.beans.yaml.extended.infrastrucutre.HostedVmInfraYaml;
import io.harness.beans.yaml.extended.infrastrucutre.HostedVmInfraYaml.HostedVmInfraSpec;
import io.harness.beans.yaml.extended.infrastrucutre.Infrastructure;
import io.harness.beans.yaml.extended.infrastrucutre.K8sDirectInfraYaml;
import io.harness.beans.yaml.extended.infrastrucutre.K8sDirectInfraYaml.K8sDirectInfraYamlSpec;
import io.harness.beans.yaml.extended.infrastrucutre.OSType;
import io.harness.beans.yaml.extended.infrastrucutre.Platform;
import io.harness.beans.yaml.extended.infrastrucutre.UseFromStageInfraYaml;
import io.harness.beans.yaml.extended.infrastrucutre.VmInfraSpec;
import io.harness.beans.yaml.extended.infrastrucutre.VmInfraYaml;
import io.harness.beans.yaml.extended.infrastrucutre.VmPoolYaml;
import io.harness.beans.yaml.extended.infrastrucutre.k8.Capabilities;
import io.harness.beans.yaml.extended.infrastrucutre.k8.SecurityContext;
import io.harness.beans.yaml.extended.infrastrucutre.k8.SecurityContextV1;
import io.harness.beans.yaml.extended.infrastrucutre.k8.Toleration;
import io.harness.beans.yaml.extended.platform.ArchType;
import io.harness.beans.yaml.extended.platform.V1.Arch;
import io.harness.beans.yaml.extended.platform.V1.OS;
import io.harness.beans.yaml.extended.platform.V1.PlatformV1;
import io.harness.beans.yaml.extended.runtime.CloudRuntime;
import io.harness.beans.yaml.extended.runtime.CloudRuntime.CloudRuntimeImageSpec;
import io.harness.beans.yaml.extended.runtime.CloudRuntime.CloudRuntimeSpec;
import io.harness.beans.yaml.extended.runtime.DockerRuntime;
import io.harness.beans.yaml.extended.runtime.DockerRuntime.DockerRuntimeSpec;
import io.harness.beans.yaml.extended.runtime.Runtime;
import io.harness.beans.yaml.extended.runtime.V1.RuntimeV1;
import io.harness.beans.yaml.extended.volumes.CIVolume;
import io.harness.beans.yaml.extended.volumes.ConfigMapVolumeYaml;
import io.harness.beans.yaml.extended.volumes.EmptyDirYaml;
import io.harness.beans.yaml.extended.volumes.HostPathYaml;
import io.harness.beans.yaml.extended.volumes.PersistentVolumeClaimYaml;
import io.harness.beans.yaml.extended.volumes.SecretVolumeYaml;
import io.harness.beans.yaml.extended.volumes.V1.CIVolumeV1;
import io.harness.beans.yaml.extended.volumes.V1.ConfigMapVolumeYamlV1;
import io.harness.beans.yaml.extended.volumes.V1.EmptyDirYamlV1;
import io.harness.beans.yaml.extended.volumes.V1.HostPathYamlV1;
import io.harness.beans.yaml.extended.volumes.V1.PersistentVolumeClaimYamlV1;
import io.harness.beans.yaml.extended.volumes.V1.SecretVolumeYamlV1;
import io.harness.cimanager.stages.V1.UnifiedStageNodeV1;
import io.harness.serializer.KryoRegistrar;
import io.harness.when.beans.StageWhenCondition;
import io.harness.yaml.core.variables.v1.ArrayNGVariableV1;
import io.harness.yaml.core.variables.v1.BooleanNGVariableV1;
import io.harness.yaml.core.variables.v1.NGVariableTypeV1;
import io.harness.yaml.core.variables.v1.NGVariableV1Wrapper;
import io.harness.yaml.core.variables.v1.NumberNGVariableV1;
import io.harness.yaml.core.variables.v1.ObjectNGVariableV1;
import io.harness.yaml.core.variables.v1.SecretNGVariableV1;
import io.harness.yaml.core.variables.v1.StageVariableV1;
import io.harness.yaml.core.variables.v1.StepVariableV1;
import io.harness.yaml.core.variables.v1.StringNGVariableV1;

import com.esotericsoftware.kryo.Kryo;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;

public class CIContractsKryoRegistrar implements KryoRegistrar {
  @Override
  public void register(Kryo kryo) {
    kryo.register(StageInfraDetails.class, 100099);
    kryo.register(CleanupStepInfo.class, 100005);
    kryo.register(RunStepInfo.class, 100011);
    kryo.register(TestStepInfo.class, 100013);
    kryo.register(CustomVariable.class, 100023);
    kryo.register(K8sDirectInfraYaml.class, 100040);
    kryo.register(CIStepOutcome.class, 100057);
    kryo.register(PluginStepInfo.class, 100058);
    kryo.register(SecurityStepInfo.class, 110105);
    kryo.register(GitCloneStepInfo.class, 110115);
    kryo.register(CustomSecretVariable.class, 100061);
    kryo.register(CustomTextVariable.class, 100062);
    kryo.register(CustomVariable.Type.class, 100063);
    kryo.register(DependencyElement.class, 100064);
    kryo.register(CIServiceInfo.class, 100065);
    kryo.register(UseFromStageInfraYaml.class, 100066);
    kryo.register(Infrastructure.Type.class, 100069);
    kryo.register(RunTestsStepInfo.class, 100075);
    kryo.register(GCRStepInfo.class, 100076);
    kryo.register(ECRStepInfo.class, 100077);
    kryo.register(DockerStepInfo.class, 100078);
    kryo.register(SaveCacheGCSStepInfo.class, 100079);
    kryo.register(RestoreCacheGCSStepInfo.class, 100080);
    kryo.register(SaveCacheS3StepInfo.class, 100081);
    kryo.register(RestoreCacheS3StepInfo.class, 100082);
    kryo.register(UploadToS3StepInfo.class, 100083);
    kryo.register(UploadToGCSStepInfo.class, 100084);
    kryo.register(UploadToArtifactoryStepInfo.class, 100086);
    kryo.register(StepArtifacts.class, 100091);
    kryo.register(PublishedFileArtifact.class, 100092);
    kryo.register(PublishedImageArtifact.class, 100093);
    kryo.register(VmInfraYaml.class, 100096);
    kryo.register(VmInfraSpec.Type.class, 110102);
    kryo.register(VmPoolYaml.class, 110103);
    kryo.register(VmPoolYamlSpec.class, 110104);
    kryo.register(HostedVmInfraYaml.class, 110112);
    kryo.register(Runtime.Type.class, 110113);
    kryo.register(CloudRuntime.class, 110114);
    kryo.register(DockerRuntime.class, 110116);
    kryo.register(DockerInfraYaml.class, 110117);

    kryo.register(K8sDirectInfraYamlSpec.class, 100041);

    kryo.register(CIVolume.class, 390005);
    kryo.register(EmptyDirYaml.class, 390006);
    kryo.register(HostPathYaml.class, 390007);
    kryo.register(PersistentVolumeClaimYaml.class, 390008);

    kryo.register(UnifiedStageNodeV1.class, 110118);
    kryo.register(StageWhenCondition.class, 110120);
    kryo.register(JsonNodeFactory.class, 110122);
    kryo.register(UnifiedEnvironmentYaml.class, 110119);

    kryo.register(PlatformV1.class, 110129);
    kryo.register(OS.class, 110130);
    kryo.register(Arch.class, 110131);
    kryo.register(RuntimeV1.class, 110132);
    kryo.register(RuntimeV1.ShellRuntimeSpec.class, 110133);
    kryo.register(RuntimeV1.VMRuntimeSpec.class, 110134);
    kryo.register(RuntimeV1.CloudRuntimeSpec.class, 110135);
    kryo.register(HostedVmInfraSpec.class, 110138);
    kryo.register(Platform.class, 110139);
    kryo.register(ArchType.class, 110140);
    kryo.register(OSType.class, 110141);
    kryo.register(DockerInfraSpec.class, 110146);
    kryo.register(NGVariableV1Wrapper.class, 110155);
    kryo.register(RunTestStepV2Info.class, 110157);
    kryo.register(StringNGVariableV1.class, 110158);
    kryo.register(NumberNGVariableV1.class, 110160);
    kryo.register(SecretNGVariableV1.class, 110161);
    kryo.register(BooleanNGVariableV1.class, 110162);
    kryo.register(ObjectNGVariableV1.class, 110163);
    kryo.register(ArrayNGVariableV1.class, 110164);
    kryo.register(CIResourceClass.class, 110170);
    kryo.register(ConfigMapVolumeYaml.class, 110183);
    kryo.register(SecretVolumeYaml.class, 110184);
    kryo.register(RuntimeV1.K8RuntimeSpec.class, 110185);
    kryo.register(SaveCacheStepInfo.class, 110186);
    kryo.register(RestoreCacheStepInfo.class, 110187);
    kryo.register(StepVariableV1.class, 110188);
    kryo.register(StageVariableV1.class, 110189);
    kryo.register(NGVariableTypeV1.class, 110190);
    kryo.register(CIVolumeV1.class, 110191);
    kryo.register(EmptyDirYamlV1.class, 110192);
    kryo.register(HostPathYamlV1.class, 110193);
    kryo.register(PersistentVolumeClaimYamlV1.class, 110194);
    kryo.register(SecretVolumeYamlV1.class, 110195);
    kryo.register(ConfigMapVolumeYamlV1.class, 110196);
    kryo.register(CIVolumeV1.Type.class, 110197);
    kryo.register(EmptyDirYamlV1Spec.class, 110198);
    kryo.register(HostPathYamlSpecV1.class, 110199);
    kryo.register(PersistentVolumeClaimYamlSpecV1.class, 110200);
    kryo.register(SecretVolumeYamlSpecV1.class, 110202);
    kryo.register(ConfigMapVolumeYamlSpecV1.class, 110203);
    kryo.register(SecurityContext.class, 110204);
    kryo.register(SecurityContextV1.class, 110205);
    kryo.register(EmptyDirYamlSpec.class, 110206);
    kryo.register(HostPathYamlSpec.class, 110207);
    kryo.register(PersistentVolumeClaimYamlSpec.class, 110208);
    kryo.register(SecretVolumeYamlSpec.class, 110209);
    kryo.register(ConfigMapVolumeYamlSpec.class, 110210);
    kryo.register(CIVolume.Type.class, 110211);
    kryo.register(PullPolicy.class, 110212);
    kryo.register(Capabilities.class, 110213);
    kryo.register(Toleration.class, 110214);
    kryo.register(UploadToHarStepInfo.class, 110215);
    kryo.register(CloudRuntimeSpec.class, 110216);
    kryo.register(CloudRuntimeImageSpec.class, 110217);
    kryo.register(DockerRuntimeSpec.class, 110220);
  }
}