# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/execution/license:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/executionconfig/api:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/yamlschema/api:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/dto:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/entities:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/metadata:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/repositories:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/outcomes:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/steps/stepinfo:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/config:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/buildstate:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/execution:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/execution/intfc:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage/utils:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/logserviceclient:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/states/codebase:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/repositories:module",
        "//878-ng-common-utilities/src/main/java/io/harness/common:module",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/listener:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/outcomes:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/sweepingoutputs:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/infrastrucutre:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/platform:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/commonconstants:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/metrics:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/metrics/helper:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/repositories:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/runner/request/builder:module",
        "//884-pms-commons/src/main/java/io/harness/pms:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events/base:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/sdk/execution/events:module",
        "//900-runner-commons/src/main/java/io/harness/runnercommons/logging:module",
        "//910-delegate-service-driver/src/main/java/io/harness/beans:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/dlite:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/taskparams:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/helper:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//951-delegate-task-commons/src/main/java/software/wings/beans:module",
        "//952-remote-observers/src/main/proto:952_remote_observers_java_proto",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/java/io/harness/ng/core/event:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/beans/summary/dto:module",
        "//960-persistence/src/main/java/io/harness/persistence:module",
        "//960-persistence/src/main/java/io/harness/queue:module",
        "//970-api-services-beans/src/main/java/io/harness/logging:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-telemetry-beans/src/main/java/io/harness/telemetry:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/tasks:module",
        "//980-commons/src/main/java/io/harness/waiter:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/api:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:javax_annotation_javax_annotation_api",
        "@maven//:javax_cache_cache_api",
        "@maven//:net_jodah_failsafe",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
