# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    resources = [
        "//925-enforcement-service/src/main/resources:resource",
        "//980-commons/src/main/resources-filtered:resource",
        "//clients/pipeline-service/pms-sdk/src/main/resources:resource",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/modules/branding/src/main/java/io/harness/branding/remote/v1/api:module",
        "//120-ng-manager/modules/branding/src/main/java/io/harness/branding/service:module",
        "//120-ng-manager/modules/branding/src/main/java/io/harness/branding/service/impl:module",
        "//120-ng-manager/modules/eula/src/main/java/io/harness/eula/outbox:module",
        "//120-ng-manager/modules/eula/src/main/java/io/harness/eula/service:module",
        "//120-ng-manager/modules/eula/src/main/java/io/harness/eula/service/impl:module",
        "//120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/ipallowlist/service:module",
        "//120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/ipallowlist/service/impl:module",
        "//120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/handler:module",
        "//120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service:module",
        "//120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/service/impl:module",
        "//120-ng-manager/modules/ldap/src/main/java/io/harness/serializer:module",
        "//120-ng-manager/modules/ng-subscriptions/src/main/java/io/harness/ngsubscriptions/service:module",
        "//120-ng-manager/modules/ng-subscriptions/src/main/java/io/harness/ngsubscriptions/service/impl:module",
        "//120-ng-manager/modules/ng-subscriptions/src/main/java/io/harness/ngsubscriptions/service/jobs:module",
        "//120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/event:module",
        "//120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/expressions/functors:module",
        "//120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/services:module",
        "//120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/services/impl:module",
        "//120-ng-manager/modules/oidc-auth/src/java/io/harness/oidc_auth/service:module",
        "//120-ng-manager/modules/oidc-auth/src/java/io/harness/oidc_auth/service/impl:module",
        "//120-ng-manager/src/main/java/io/harness/changestreams/controllers:module",
        "//120-ng-manager/src/main/java/io/harness/changestreams/redisconsumers:module",
        "//120-ng-manager/src/main/java/io/harness/ng:module",
        "//120-ng-manager/src/main/java/io/harness/ng/ait:module",
        "//120-ng-manager/src/main/java/io/harness/ng/aitestautomation:module",
        "//120-ng-manager/src/main/java/io/harness/ng/code/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/code/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/agent/client:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/aiagent/imports:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/cache:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/utils:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/delegate/client:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/entityactivity/event:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/entitysetupusage/event:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/listener:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/listener/gitops:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/service:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/exceptionmappers:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/handler/freezeHandlers:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/helpers:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/iterator:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/licensedmodules/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/licenseusage/event:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/migration:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/migration/customdeployment:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/modules:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/onboarding:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/onboarding/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/onboarding/services/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/outbox:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/perpetualtask/entityreference:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/provider/resources:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/refresh/service:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/remote/licenserestriction:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/scheduler:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/smtp:module",
        "//120-ng-manager/src/main/java/io/harness/ng/eventsframework:module",
        "//120-ng-manager/src/main/java/io/harness/ng/feedback/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/feedback/services/impls:module",
        "//120-ng-manager/src/main/java/io/harness/ng/gitops/changestreams:module",
        "//120-ng-manager/src/main/java/io/harness/ng/gitops/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/gitops/kafka:module",
        "//120-ng-manager/src/main/java/io/harness/ng/gitops/service:module",
        "//120-ng-manager/src/main/java/io/harness/ng/har:module",
        "//120-ng-manager/src/main/java/io/harness/ng/iac:module",
        "//120-ng-manager/src/main/java/io/harness/ng/iro:module",
        "//120-ng-manager/src/main/java/io/harness/ng/iro/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/loadtest:module",
        "//120-ng-manager/src/main/java/io/harness/ng/migration:module",
        "//120-ng-manager/src/main/java/io/harness/ng/modules/constants:module",
        "//120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo:module",
        "//120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/runnable:module",
        "//120-ng-manager/src/main/java/io/harness/ng/moduleversioninfo/service:module",
        "//120-ng-manager/src/main/java/io/harness/ng/monitoringmanager:module",
        "//120-ng-manager/src/main/java/io/harness/ng/oauth:module",
        "//120-ng-manager/src/main/java/io/harness/ng/opa/entities/apiKey:module",
        "//120-ng-manager/src/main/java/io/harness/ng/opa/entities/serviceaccount:module",
        "//120-ng-manager/src/main/java/io/harness/ng/opa/entities/token:module",
        "//120-ng-manager/src/main/java/io/harness/ng/opa/entities/usergroup:module",
        "//120-ng-manager/src/main/java/io/harness/ng/opa/entities/variable:module",
        "//120-ng-manager/src/main/java/io/harness/ng/overview/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/overview/eventGenerator:module",
        "//120-ng-manager/src/main/java/io/harness/ng/overview/service:module",
        "//120-ng-manager/src/main/java/io/harness/ng/privateconnectivity:module",
        "//120-ng-manager/src/main/java/io/harness/ng/privateconnectivity/resources:module",
        "//120-ng-manager/src/main/java/io/harness/ng/privateconnectivity/sanitizer:module",
        "//120-ng-manager/src/main/java/io/harness/ng/rollback:module",
        "//120-ng-manager/src/main/java/io/harness/ng/scim:module",
        "//120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/notifications:module",
        "//120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/api:module",
        "//120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/servicediscovery:module",
        "//120-ng-manager/src/main/java/io/harness/ng/smp/resources:module",
        "//120-ng-manager/src/main/java/io/harness/ng/sto:module",
        "//120-ng-manager/src/main/java/io/harness/ng/support/client:module",
        "//120-ng-manager/src/main/java/io/harness/ng/tunnel/services/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/validator/service:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/services/api:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/services/impl:module",
        "//120-ng-manager/src/main/java/io/harness/pms/expressions/functors:module",
        "//120-ng-manager/src/main/java/io/harness/pms/kafkaconsumer:module",
        "//120-ng-manager/src/main/java/io/harness/pms/redisConsumer:module",
        "//120-ng-manager/src/main/java/io/harness/serializer:module",
        "//120-ng-manager/src/main/java/io/harness/telemetry:module",
        "//122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings:module",
        "//122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings/resources:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol/user:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/api/impl:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/migration:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/outbox:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/remote:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/exception/mapper:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/service:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/service/impl:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/migration:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/userprofile/entities:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/userprofile/event:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/userprofile/services/impl:module",
        "//125-cd-nextgen/modules/ai-verify/src/main/java/io/harness/cdng/aiverify:module",
        "//125-cd-nextgen/modules/common/contracts/src/main/java/io/harness/cdng/pipeline/resources:module",
        "//125-cd-nextgen/modules/common/contracts/src/main/java/io/harness/cdng/stage/resources:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/customDeployment/eventlistener:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/beans:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/stage/resources:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/driftdetection/listener:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/enforcement/executions:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/ng:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/perpetualtask/entityreference:module",
        "//125-cd-nextgen/modules/dbdevops/src/main/java/io/harness/cdng/dbdevops/services:module",
        "//125-cd-nextgen/src/main/java/io/harness/cd/license:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/bamboo:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/creator:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/creator/filters:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/driftdetection:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/driftdetection/resource:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/fileservice:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/gitSync:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/jenkins/jenkinsstep:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/licenserestriction:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/migration:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/oidc:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/orchestration:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/events:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/pipeline/executions/events/backfill:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform/functor:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/functor:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/usage/common/jobs:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/usage/common/task:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/usage/v2/resource:module",
        "//125-cd-nextgen/src/main/java/io/harness/pms/governance:module",
        "//125-cd-nextgen/src/main/java/io/harness/pms/inputmetadata:module",
        "//125-cd-nextgen/src/main/java/io/harness/polling/bean:module",
        "//125-cd-nextgen/src/main/java/io/harness/polling/service/impl:module",
        "//125-cd-nextgen/src/main/java/io/harness/polling/service/intfc:module",
        "//125-cd-nextgen/src/main/java/io/harness/registrars:module",
        "//125-cd-nextgen/src/main/java/io/harness/telemetry:module",
        "//125-cd-nextgen/src/main/java/io/harness/telemetry/service:module",
        "//125-cd-nextgen/src/main/java/io/harness/timescale:module",
        "//125-freeze/src/main/java/io/harness:module",
        "//125-freeze/src/main/java/io/harness/freeze:module",
        "//125-freeze/src/main/java/io/harness/freeze/service:module",
        "//125-freeze/src/main/java/io/harness/freeze/service/impl:module",
        "//126-instance/src/main/java/io/harness/iterator/module",
        "//126-instance/src/main/java/io/harness/listeners:module",
        "//126-instance/src/main/java/io/harness/migrations:module",
        "//126-instance/src/main/java/io/harness/migrations/timescale/job:module",
        "//126-instance/src/main/java/io/harness/runnable:module",
        "//126-instance/src/main/java/io/harness/service:module",
        "//126-instance/src/main/java/io/harness/service/deploymentevent:module",
        "//126-instance/src/main/java/io/harness/service/instancesyncperpetualtask:module",
        "//126-instance/src/main/java/io/harness/service/stats/statscollector:module",
        "//126-instance/src/main/java/io/harness/service/stats/usagemetrics/eventconsumer:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/entitymetadata:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/opa/environment:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/opa/gitx:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/opa/infrastructure:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/opa/override:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/opa/service:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/utils:module",
        "//128-resiliencetesting/src/main/java/io/harness/ng/chaos:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/caching/resource:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/common/events:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/common/service:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/configurations:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/core/fullsync:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/core/runnable:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/createbranchevent:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/core/webhook/pushevent:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/gitbackedentities:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/gitbackedentities/providers:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/listener:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/observer:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/resource:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/gitxtriggerexecution:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/gitxwebhook:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/migration:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/server:module",
        "//332-iacm-common/src/main/java/io/harness/iacmserviceclient:module",
        "//332-idp/src/main/java/io/harness/steps/beans/stepinfo:module",
        "//332-idp/src/main/java/io/harness/steps/beans/stepnode:module",
        "//400-rest-commons/src/main/java/io/harness/serializer:module",
        "//400-rest-commons/src/main/java/software/wings/app:module",
        "//420-delegate-service/src/main/java/io/harness/metrics/impl:module",
        "//420-delegate-service/src/main/java/io/harness/metrics/intfc:module",
        "//420-delegate-service/src/main/java/io/harness/module",
        "//420-delegate-service/src/main/java/io/harness/runner/metrics/impl:module",
        "//420-delegate-service/src/main/java/io/harness/runner/metrics/intfc:module",
        "//440-certificate-nextgen/src/main/java/io/harness:module",
        "//440-certificate-nextgen/src/main/java/io/harness/ngcertificates/outbox/events:module",
        "//440-certificate-nextgen/src/main/java/io/harness/ngcertificates/services:module",
        "//440-certificate-nextgen/src/main/java/io/harness/ngcertificates/services/impl:module",
        "//440-connector-nextgen/contracts/openapi/v1:connector-server-spec-module",
        "//440-connector-nextgen/src/main/java/io/harness/connector:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/apis/resource:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/entities:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/events:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/opa:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/services:module",
        "//440-connector-nextgen/src/main/java/io/harness/ng/core/event/listener:module",
        "//440-secret-management-service/src/main/java/io/harness/ng/core/event/listener:module",
        "//440-secret-management-service/src/main/java/io/harness/ng/core/outbox:module",
        "//440-secret-management-service/src/main/java/io/harness/ng/filter:module",
        "//440-secret-management-service/src/main/java/io/harness/secretmanager/handler:module",
        "//445-gitops/src/main/java/io/harness:module",
        "//445-gitops/src/main/java/io/harness/events/base:module",
        "//867-polling-contracts/src/main/java/io/harness/polling/client:module",
        "//874-orchestration-delay/src/main/java/io/harness/delay:module",
        "//877-filestore/src/main/java/io/harness/filestore:module",
        "//877-filestore/src/main/java/io/harness/filestore/events/listener:module",
        "//877-filestore/src/main/java/io/harness/filestore/outbox:module",
        "//878-ng-common-utilities/src/main/java/io/harness:module",
        "//878-ng-common-utilities/src/main/java/io/harness/engine/expressions:module",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/ngmanager:module",
        "//878-ng-common-utilities/src/main/java/io/harness/opa:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/listener:module",
        "//878-ng-common-utilities/src/main/java/io/harness/transientData:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo/V1:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/cd/core:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/platform/V1:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/buildstate:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/steps/plugin/infrastructure/volumes:module",
        "//884-pms-commons/src/main/java/io/harness/expression:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events/base:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/api:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/encryptors:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/events:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/sdk:module",
        "//910-delegate-service-driver/src/main/java/io/harness/client:module",
        "//910-delegate-service-driver/src/main/java/io/harness/grpc:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service/impl:module",
        "//920-delegate-service-beans/src/main/java/io/harness/delegate/beans:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//920-ng-signup/src/main/java/io/harness/signup/clients:module",
        "//920-ng-signup/src/main/java/io/harness/signup/resources:module",
        "//920-ng-signup/src/main/java/io/harness/signup/services/impl:module",
        "//925-enforcement-service/src/main/java/io/harness/enforcement:module",
        "//925-enforcement-service/src/main/java/io/harness/enforcement/outbox:module",
        "//925-enforcement-service/src/main/java/io/harness/enforcement/resource:module",
        "//925-enforcement-service/src/main/java/io/harness/enforcement/services:module",
        "//930-ng-core-clients/src/main/java/io/harness/code:module",
        "//930-ng-core-clients/src/main/java/io/harness/connector:module",
        "//930-ng-core-clients/src/main/java/io/harness/entitysetupusageclient:module",
        "//930-ng-core-clients/src/main/java/io/harness/environment:module",
        "//930-ng-core-clients/src/main/java/io/harness/gitops:module",
        "//930-ng-core-clients/src/main/java/io/harness/infrastructure:module",
        "//930-ng-core-clients/src/main/java/io/harness/modules:module",
        "//930-ng-core-clients/src/main/java/io/harness/monitoredservice:module",
        "//930-ng-core-clients/src/main/java/io/harness/oidc:module",
        "//930-ng-core-clients/src/main/java/io/harness/organization:module",
        "//930-ng-core-clients/src/main/java/io/harness/overrides:module",
        "//930-ng-core-clients/src/main/java/io/harness/project:module",
        "//930-ng-core-clients/src/main/java/io/harness/runner/cgi:module",
        "//930-ng-core-clients/src/main/java/io/harness/runner/plugin:module",
        "//930-ng-core-clients/src/main/java/io/harness/secrets:module",
        "//930-ng-core-clients/src/main/java/io/harness/service:module",
        "//930-ng-core-clients/src/main/java/io/harness/sso:module",
        "//930-ng-core-clients/src/main/java/io/harness/user:module",
        "//930-ng-core-clients/src/main/java/io/harness/zendesk:module",
        "//930-ng-license-manager/src/main/java/io/harness/credit/resource:module",
        "//930-ng-license-manager/src/main/java/io/harness/credit/schedular:module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/api/resource:module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/event/listener:module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/migrations:module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/outbox:module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/services:module",
        "//930-ng-license-manager/src/main/java/io/harness/subscription:module",
        "//930-ng-license-manager/src/main/java/io/harness/subscription/resource:module",
        "//931-encryption-service/src/java/io/harness/encryptors/clients:module",
        "//932-connector-task/src/main/java/io/harness/connector/helper:module",
        "//937-persistence-tracer/src/main/java/io/harness/tracing:module",
        "//940-feature-flag/src/main/java/io/harness/ff:module",
        "//940-primary-version-manager/src/main/java/io/harness/app:module",
        "//940-primary-version-manager/src/main/java/io/harness/controller:module",
        "//940-primary-version-manager/src/main/java/io/harness/resource:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/custom:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/example:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/resources:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/servicedependencies:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/services:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/usage:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/constants:module",
        "//947-scim-core/src/main/io/harness/scim/service:module",
        "//950-delegate-task-sdk/java/io/harness/task/response/module",
        "//950-log-client/src/main/java/io/harness/logstreaming:module",
        "//950-ng-core/src/main/java/io/harness/ng/userprofile/commons:module",
        "//950-ng-core/src/main/java/io/harness/ng/userprofile/services/api:module",
        "//950-ng-core/src/main/java/io/harness/ng/validator/service/api:module",
        "//950-ng-core/src/main/java/io/harness/ng/webhook/services/api:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/impl:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/licenserestriction:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/migration:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/modules:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/outbox:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//950-opa-client/src/main/java/io/harness/opaclient:module",
        "//950-telemetry/src/main/java/io/harness/telemetry:module",
        "//950-telemetry/src/main/java/io/harness/telemetry/filter:module",
        "//950-wait-engine/src/main/java/io/harness/serializer:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//950-wait-engine/src/main/java/io/harness/waiter/module",
        "//950-wait-engine/src/main/java/io/harness/waiter/nrcsp:module",
        "//950-wait-engine/src/main/java/io/harness/waiter/persistence:module",
        "//952-remote-observers/src/main/java/io/harness/observer:module",
        "//952-remote-observers/src/main/java/io/harness/observer/consumer:module",
        "//952-scm-java-client/src/main/java/io/harness:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/ng/core/event:module",
        "//953-yaml-commons/src/main/java/io/harness/plancreator/stages:module",
        "//953-yaml-commons/src/main/java/io/harness/plancreator/stages/parallel:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/core:module",
        "//954-connector-beans/src/main/java/io/harness/connector:module",
        "//955-account-mgmt/src/main/java/io/harness/account:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/mapper:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/resource:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/task:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/api:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/eventpoll:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/module",
        "//955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage:module",
        "//958-migration-sdk/src/main/java/io/harness/migration/ng:module",
        "//958-ng-file-service-sdk/src/main/java/io/harness/file:module",
        "//959-file-service-commons/src/main/java/software/wings/service/impl:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//960-api-services/src/main/java/io/harness/aitestautomation/client:module",
        "//960-api-services/src/main/java/io/harness/aitestautomation/service:module",
        "//960-continuous-features/src/main/java/io/harness/cf:module",
        "//960-continuous-features/src/main/java/io/harness/ff:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers:module",
        "//960-ng-license-beans/src/main/java/io/harness/ccm/license/remote:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/remote:module",
        "//960-persistence/src/main/java/io/harness/alloydb:module",
        "//960-persistence/src/main/java/io/harness/cache:module",
        "//960-persistence/src/main/java/io/harness/iterator:module",
        "//960-persistence/src/main/java/io/harness/lock:module",
        "//960-persistence/src/main/java/io/harness/mongo:module",
        "//960-persistence/src/main/java/io/harness/ng/userprovider:module",
        "//960-persistence/src/main/java/io/harness/persistence:module",
        "//960-persistence/src/main/java/io/harness/persistence/api:module",
        "//960-persistence/src/main/java/io/harness/queue:module",
        "//960-persistence/src/main/java/io/harness/redis:module",
        "//960-persistence/src/main/java/io/harness/timescaledb:module",
        "//960-persistence/src/main/java/io/harness/timescaledb/metrics:module",
        "//960-persistence/src/main/java/io/harness/timescaledb/retention:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml/schema/beans:module",
        "//965-ng-filter/src/main/java/io/harness/security:module",
        "//965-ng-filter/src/main/java/io/harness/token:module",
        "//965-ng-filter/src/main/java/io/harness/token/remote:module",
        "//970-api-services-beans/src/main/java/io/harness/encryptors:module",
        "//970-api-services-beans/src/main/java/io/harness/filter:module",
        "//970-grpc/src/main/java/io/harness/grpc/client:module",
        "//970-grpc/src/main/java/io/harness/grpc/interceptor:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/cd:module",
        "//970-ng-commons/src/main/java/io/harness/circuitbreaker/utils:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/filter:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/jobs:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/modules:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/filter:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/metrics:module",
        "//970-ng-commons/src/main/java/io/harness/remote:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/request:module",
        "//970-ng-commons/src/main/java/io/harness/security/annotations:module",
        "//970-ng-commons/src/main/java/io/serializer/mapper:module",
        "//970-telemetry-beans/src/main/java/io/harness/telemetry:module",
        "//980-commons/src/main/java/io/harness/annotations:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/aws/retrypolicy:module",
        "//980-commons/src/main/java/io/harness/configuration:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler:module",
        "//980-commons/src/main/java/io/harness/fips:bouncycastle",
        "//980-commons/src/main/java/io/harness/fips:bouncycastle_fips",
        "//980-commons/src/main/java/io/harness/govern:module",
        "//980-commons/src/main/java/io/harness/health:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/logstreaming:module",
        "//980-commons/src/main/java/io/harness/maintenance:module",
        "//980-commons/src/main/java/io/harness/manage:module",
        "//980-commons/src/main/java/io/harness/metrics:module",
        "//980-commons/src/main/java/io/harness/morphia:module",
        "//980-commons/src/main/java/io/harness/reflection:module",
        "//980-commons/src/main/java/io/harness/resilience/utils:module",
        "//980-commons/src/main/java/io/harness/secret:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/annotations:module",
        "//980-commons/src/main/java/io/harness/security/mesh:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/serializer/kryo:module",
        "//980-commons/src/main/java/io/harness/threading:module",
        "//980-commons/src/main/java/io/harness/time:module",
        "//980-commons/src/main/java/io/harness/version:module",
        "//980-commons/src/main/java/software/wings/jersey:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/admin/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/aggregator/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/health:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/permissions/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/preference/api:module",
        "//access-control/contracts/openapi/v1:access-control-server-spec-module",
        "//access-control/contracts/openapi/v1/resourcegroup:resource-group-server-spec-module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol:module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol/migration:module",
        "//clients/access-control/sdk/src/main/java/io/harness:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol/filter:module",
        "//clients/accountresourceng/src/main/java/io/harness/accountresourceng:module",
        "//clients/audit/src/main/java/io/harness/audit/client/remote:module",
        "//clients/directory-service/src/main/java/io/harness/ds/remote:module",
        "//clients/fme/src/main/java/io/harness/fme:module",
        "//clients/har/src/io/harness/harclient:module",
        "//clients/harnessid/src/main/java/io/harness/harnessid/client:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//clients/notification/src/main/java/io/harness/notification:module",
        "//clients/notification/src/main/java/io/harness/notification/module",
        "//clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote:module",
        "//clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/triggers:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/governance:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/events:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/expression/sdk:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/governance:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/handler:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/waiter:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/waiter:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/configuration:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/facilitators:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/interrupts:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/advise:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/resume:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/start:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/plan:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/progress:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/metrics:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/beans:module",
        "//clients/resource-group/src/main/java/io/harness/resourcegroupclient:module",
        "//clients/scope/src/main/java/io/harness/scopeinfoclient:module",
        "//clients/scope/src/main/java/io/harness/scopeinfoclient/remote:module",
        "//clients/template-service/src/main/java/io/harness/template:module",
        "//connector-oidc/src/main/java/io/harness/connector/oidc:module",
        "//favorites/src/main/java/io/harness/favorites/services:module",
        "//favorites/src/main/java/io/harness/favorites/services/impl:module",
        "//license-manager/src/main/java/io/harness/modules:module",
        "//license-manager/src/main/java/io/harness/services:module",
        "//ng-banners/src/main/java/io/harness/ngbanners/outbox/events:module",
        "//ng-banners/src/main/java/io/harness/ngbanners/outbox/handler:module",
        "//ng-banners/src/main/java/io/harness/ngbanners/services:module",
        "//ng-banners/src/main/java/io/harness/ngbanners/services/impl:module",
        "//ng-settings/src/main/java/io/harness/ngsettings:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/outbox:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/services:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/services/impl:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/settings:module",
        "//oidc-core/src/main/java/io/harness/oidc/config:module",
        "//oidc-core/src/main/java/io/harness/oidc/gcp/utility:module",
        "//oidc-core/src/main/java/io/harness/oidc/helpers:module",
        "//oidc-core/src/main/java/io/harness/oidc/jwks:module",
        "//oidc-core/src/main/java/io/harness/oidc/rsa:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/serializer/json:module",
        "//platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit:module",
        "//platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit/remote:module",
        "//platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/remote/resources:module",
        "//secrets-connectors-service/service/src/main/java/io/harness/ng/core/outbox:module",
        "//srm-service/modules/cv-nextgen-service/contracts/api/src/main/java/io/harness/cvng/client:module",
        "//template-service/contracts/openapi/v1:template-server-spec-module",
        "//template-service/contracts/src/main/java/io/harness/template/health:module",
        "//template-service/contracts/src/main/java/io/harness/template/resources:module",
        "//template-service/contracts/src/main/java/io/harness/template/resources/beans/yaml:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:io_dropwizard_dropwizard_configuration",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:io_dropwizard_dropwizard_jackson",
        "@maven//:io_dropwizard_dropwizard_jersey",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:io_dropwizard_metrics_metrics_servlets",
        "@maven//:io_swagger_core_v3_swagger_jaxrs2",
        "@maven//:jakarta_servlet_jakarta_servlet_api",
        "@maven//:jakarta_ws_rs_jakarta_ws_rs_api",
        "@maven//:javax_cache_cache_api",
        "@maven//:javax_validation_validation_api",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_eclipse_jetty_jetty_servlets",
        "@maven//:org_glassfish_hk2_hk2_api",
        "@maven//:org_glassfish_jersey_core_jersey_server",
        "@maven//:org_glassfish_jersey_media_jersey_media_multipart",
        "@maven//:org_hibernate_validator_hibernate_validator",
        "@maven//:org_jooq_jooq",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_core",
        "@maven//:org_springframework_spring_tx",
        "@maven//:ru_vyarus_guice_validator",
    ],
)

java_binary(
    name = "NextGenApplication",
    main_class = "io.harness.ng.modules.NextGenApplication",
    visibility = ["//visibility:public"],
    runtime_deps = [":module"],
    deps = [],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*.java"]),
    sonarqube_srcs = glob(["*"]),
)
