# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("//:tools/bazel/harness.bzl", "java_library")

java_library(
    name = "module",
    srcs = glob(["**/*.java"]),
    resources = [],
    visibility = ["//idp-service:__subpackages__"],
    deps = [
        "//:lombok",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol/filter:module",
        "//idp-service/src/main/java/io/harness/idp/catalog/entities:module",
        "//idp-service/src/main/java/io/harness/idp/catalog/graph/beans:module",
        "//idp-service/src/main/java/io/harness/idp/catalog/helpers:module",
        "//idp-service/src/main/java/io/harness/idp/common:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
    ],
)
