# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis_for_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    data = [
        "//120-ng-manager/src/test/resources:resource",
    ],
    resources = [
        "//120-ng-manager/src/test/resources:resource",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/utils:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/beans:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/dto:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/remote:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/entities:module",
        "//440-secret-management-service/contracts/openapi/v1:secret-server-spec-module",
        "//440-secret-management-service/src/main/java/io/harness/ng/core/api/impl:module",
        "//440-secret-management-service/src/main/java/io/harness/ng/core/dto:module",
        "//440-secret-management-service/src/main/java/io/harness/ng/core/remote:module",
        "//440-secret-management-service/src/main/java/io/harness/secret/services/impl:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/api:module",
        "//890-sm-core/src/main/java/software/wings/service/impl/security:module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/services:module",
        "//940-feature-flag/src/main/java/io/harness/ff:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core/api:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/ng/core:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/secretmanagerclient:module",
        "//950-ng-core/src/main/java/io/harness/ng/validator/dto:module",
        "//950-ng-core/src/main/java/io/harness/ng/validator/service/api:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/impl:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/remote:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules:module",
        "//960-persistence:supporter-test",
        "//960-persistence/src/main/java/io/harness/utils:module",
        "//970-api-services-beans/src/main/java/io/harness/security/encryption:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/encryption:module",
        "//970-ng-commons/src/main/java/io/harness/entities:module",
        "//970-ng-commons/src/main/java/io/harness/ng/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/common/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/dto:module",
        "//970-ng-commons/src/main/java/io/harness/secrets:module",
        "//970-ng-commons/src/main/java/io/serializer/mapper:module",
        "//980-commons/src/main/java/io/harness/beans:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/health:module",
        "//980-commons/src/main/java/io/harness/maintenance:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/threading:module",
        "//990-commons-test/src/main/java/io/harness:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "//999-annotations/src/main/java/io/harness/agent/sdk:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/scope/src/main/java/io/harness/scopeinfoclient/remote:module",
        "//favorites/contracts/src/main/java/io/harness/favorites:module",
        "//favorites/src/main/java/io/harness/favorites/entities:module",
        "//favorites/src/main/java/io/harness/favorites/services:module",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_intellij_annotations",
        "@maven//:com_squareup_retrofit2_retrofit",
        "@maven//:io_dropwizard_dropwizard_jersey",
        "@maven//:io_dropwizard_metrics_metrics_healthchecks",
        "@maven//:javax_cache_cache_api",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:junit_junit",
        "@maven//:net_sf_json_lib_json_lib",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_springframework_data_spring_data_commons",
    ],
)

run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

run_tests("*Test.java")
