# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis_for_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    resources = [
        "//332-ci-manager/service/src/main/resources/templates/configFiles:resource",
        "//332-ci-manager/service/src/test/resources:resource",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//332-ci-manager/service/src/main/java/io/harness/ci/cd/service:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/common:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/app/beans/entities:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/cd/beans/outcomes:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/cdng/artifact/outcome:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/states/helpers:module",
        "//878-ng-common-utilities/src/main/java/io/harness/beans/common:module",
        "//878-ng-common-utilities/src/main/java/io/harness/configFiles:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/rbac:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/runner/request/helpers:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/runner/request/helpers/infra:module",
        "//880-pipeline-cd-commons/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/expression:module",
        "//930-ng-core-clients/src/main/java/io/harness/envgroup/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/envgroup/unified:module",
        "//930-ng-core-clients/src/main/java/io/harness/environment/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/infrastructure:module",
        "//930-ng-core-clients/src/main/java/io/harness/infrastructure/unified:module",
        "//930-ng-core-clients/src/main/java/io/harness/overrides:module",
        "//930-ng-core-clients/src/main/java/io/harness/unified/service:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/environment/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/serviceoverridev2/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/unified/cd/infrastructure:module",
        "//960-ng-core-beans/src/main/java/io/harness/unified/cd/service/artifacts:module",
        "//960-ng-core-beans/src/main/java/io/harness/unified/cd/service/configfiles:module",
        "//960-ng-core-beans/src/main/java/io/harness/unified/cd/service/manifests:module",
        "//960-ng-core-beans/src/main/java/io/harness/unified/cd/service/overrides:module",
        "//960-ng-core-beans/src/main/java/io/harness/unified/cd/service/spec:module",
        "//960-ng-core-beans/src/main/java/io/harness/unified/cd/service/startupscript:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/interceptor:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/entitydetail:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/proto:970_ng_java_contract_proto",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/data:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/outputs:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/steps/io:module",
        "//pipeline-service/modules/pms-contracts/src/main/proto:pms_contracts_java_proto",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
    ],
)

run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

run_tests("*Test.java")
