# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//323-sto-utilities/src/main/java/io/harness/stoserviceclient:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/beans/steps/stepinfo:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/execution/license:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/dependencies:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/entities:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/outcomes:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/enforcement:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/artifactDetails:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/utils:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/validation:module",
        "//332-ssca/ci/src/main/java/io/harness/ssca/execution:module",
        "//332-ssca/ci/src/main/java/io/harness/ssca/execution/provenance:module",
        "//332-ssca/commons/src/main/java/io/harness/ssca/beans:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/app/beans/entities:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/environment:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/outcomes:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/stages/parameters:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/steps/stepinfo:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/buildstate:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/execution/intfc:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/states:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/utils/ci:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/repositories:module",
        "//878-ng-common-utilities/src/main/java/io/harness/common:module",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/rbac:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps/executable:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps/matrix:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/build:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/execution:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/execution/artifact:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/outcomes:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/provenance:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/serializer:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/outcome:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/sweepingoutputs:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/infrastrucutre:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/commonconstants:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/metrics:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/execution:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/dlite:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/stepstatus/artifact:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/helper:module",
        "//951-delegate-task-commons/src/main/java/io/harness/delegate/beans:module",
        "//951-delegate-task-commons/src/main/java/software/wings/beans:module",
        "//953-yaml-commons/src/main/java/io/harness/plancreator/execution:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/v1:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/extended/ci/codebase:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/registry:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-common-entities/src/main/java/io/harness/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/beans/summary/dto:module",
        "//960-persistence/src/main/java/io/harness/persistence:module",
        "//970-api-services-beans/src/main/java/io/harness/k8s/model:module",
        "//970-api-services-beans/src/main/java/io/harness/logging:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/entitydetail:module",
        "//970-ng-commons/src/main/java/io/harness/plancreator/steps:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//970-ng-commons/src/main/java/io/harness/yaml/core/timeout:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/encoding:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/supplier:module",
        "//980-commons/src/main/java/io/harness/tasks:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_inject_guice",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_codehaus_groovy_groovy",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
