# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//930-delegate-tasks/src/main/java/io/harness/delegate/task/shell:module",
        "//930-ng-core-clients/src/main/java/io/harness/organization/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/project/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/usergroups:module",
        "//953-yaml-commons/src/main/java/io/harness/notification:module",
        "//953-yaml-commons/src/main/java/io/harness/notification/channelDetails:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/utils:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/template:module",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/common:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/common/beans:module",
        "//970-ng-commons/src/main/java/io/harness/notification:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//970-ng-commons/src/main/java/io/harness/utils/yaml:module",
        "//980-commons/src/main/java/io/harness/beans/user:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/gitcaching:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/sanitizer:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/notification/src/main/java/io/harness/notification/channeldetails:module",
        "//clients/notification/src/main/java/io/harness/notification/notificationclient:module",
        "//clients/notification/src/main/java/io/harness/notification/templates:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/notification/bean:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/harness/beans:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities:module",
        "//pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans:module",
        "//pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans/dto:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/eventlog:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/notificationEventLog:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution:module",
        "//pipeline-service/service/src/main/java/io/harness/pipeline/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/notification/stagemetadata:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/notification/stagemetadata/summary:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/notification/summary:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/helpers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/enforcement:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/yaml:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/utils:module",
        "//platform-service/modules/notification-service/contracts/src/main/java/io/harness/notification/entities:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
