# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/modules/ip-allowlist/src/main/java/io/harness/repositories/ipallowlist/custom:module",
        "//120-ng-manager/src/main/java/io/harness/ng:module",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/handler:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/manager:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/service:module",
        "//120-ng-manager/src/main/java/io/harness/repositories/ng/core/spring:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/services:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/perpetualtask/entityreference:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/repositories/executions:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/repositories/instance:module",
        "//125-cd-nextgen/modules/dbdevops/src/main/java/io/harness/cdng/dbdevops/step/service:module",
        "//125-cd-nextgen/src/main/java/io/harness/polling/service/intfc:module",
        "//125-freeze/src/main/java/io/harness/freeze/service:module",
        "//126-instance/src/main/java/io/harness/entities:module",
        "//126-instance/src/main/java/io/harness/repositories/deploymentsummary:module",
        "//126-instance/src/main/java/io/harness/service/infrastructuremapping:module",
        "//126-instance/src/main/java/io/harness/service/instance:module",
        "//126-instance/src/main/java/io/harness/service/instancesyncperpetualtaskinfo:module",
        "//126-instance/src/main/java/io/harness/service/releasedetailsmapping:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/gitops/service:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/services:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/services:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/service:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/utils:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/eventHandlers:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/validator:module",
        "//440-connector-nextgen/src/main/java/io/harness/ng/core/event/manager:module",
        "//440-secret-management-service/src/main/java/io/harness/repositories/ng/core/spring:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/api:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core/api:module",
        "//950-ng-core/src/main/java/io/harness/repositories/activityhistory:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/impl:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/ng/core/event:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/service:module",
        "//959-ng-persistence/src/main/java/io/harness/mongo/helper:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//959-psql-database-models:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user:module",
        "//960-persistence/src/main/java/io/harness/persistence/api:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/metrics:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/recorder:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/annotations:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/iromanager/remote/connectors/zoom:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/services:module",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_intellij_annotations",
        "@maven//:javax_cache_cache_api",
        "@maven//:net_jodah_failsafe",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_jooq_jooq",
        "@maven//:org_mongodb_bson",
        "@maven//:org_reflections_reflections",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
