# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/modules/ip-allowlist/contracts/src/main/java/io/harness/ipallowlist/entity:module",
        "//120-ng-manager/modules/ng-variables/src/main/java/io/harness/ng/core/variable/entity:module",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/entities:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/entities/migration:module",
        "//120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/entities:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/invites/entities:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/entities:module",
        "//125-cd-nextgen/modules/azure/core/src/main/java/io/harness/cdng/provision/azure/beans:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/creator/plan/stage:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/execution:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/instance:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/provision/terraform/executions:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/polling/bean:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/common/aws/entity:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/k8s/trafficrouting:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/provision/awscdk/beans:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/provision/cloudformation/beans:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraform:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/provision/terraformcloud/dal:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/provision/terragrunt:module",
        "//125-freeze/src/main/java/io/harness/freeze/entity:module",
        "//126-instance/src/main/java/io/harness/entities:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/infrastructure/entity:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/security:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/entity:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity:module",
        "//440-connector-nextgen/src/main/java/io/harness/ng/core/event/manager:module",
        "//440-connector-nextgen/src/main/java/io/harness/ng/core/migration:module",
        "//877-filestore/src/main/java/io/harness/filestore/entities:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/api:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/models:module",
        "//890-sm-delegate/src/main/java/io/harness/ng/core/entities:module",
        "//931-encryption-service/src/java/io/harness/exception:module",
        "//931-secret-providers/src/java/io/harness/helpers:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core/api:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/awskms:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/config:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/remote:module",
        "//950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services:module",
        "//950-ng-core/src/main/java/io/harness/ng/core/activityhistory/entity:module",
        "//950-ng-core/src/main/java/io/harness/ng/core/licenseusage/entities:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/repositories/core/spring:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//955-account-mgmt/src/main/java/io/harness/account/utils:module",
        "//955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service:module",
        "//958-migration-sdk/src/main/java/io/harness/migration/beans:module",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//960-persistence/src/main/java/io/harness/mongo:module",
        "//960-persistence/src/main/java/io/harness/mongo/index:module",
        "//960-persistence/src/main/java/io/harness/persistence:module",
        "//960-persistence/src/main/java/io/harness/persistence/api:module",
        "//960-persistence/src/main/java/io/harness/persistence/store:module",
        "//970-api-services-beans/src/main/java/io/harness/git/model:module",
        "//970-api-services-beans/src/main/java/io/harness/security/encryption:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/encryption:module",
        "//970-ng-commons/src/main/java/io/harness/ng/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/common/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/metrics:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/maintenance:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol:module",
        "//clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote:module",
        "//clients/scope/src/main/java/io/harness/scopeinfoclient/remote:module",
        "//favorites/src/main/java/io/harness/favorites/entities:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/entities:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/services:module",
        "//ng-settings/src/main/java/io/harness/repositories/ngsettings/spring:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_intellij_annotations",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:io_dropwizard_dropwizard_lifecycle",
        "@maven//:javax_cache_cache_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_mongodb_mongo_java_driver",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

# run static analysis macro for pmd/checkstyle/sonarqube checks
run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
