# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_binary")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis")

java_library(
    name = "module",
    resources = [
        "//pipeline-service/modules/orchestration-steps/src/main/resources:resource",
    ],
    visibility = [
        "//125-cd-nextgen:__subpackages__",
        "//pipeline-service:__subpackages__",
    ],
    exports = [
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/cf/pipeline:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/event:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/filters:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/agent:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipelinerollback:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/dynamic/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/barrier:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/changeadvisor/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/email:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/email/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/pluginstep:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/resourceconstraint:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/pms/sdk/core/pipeline/variables:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/registrars:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/repositories:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/kryo:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/serializer/morphia:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/ssca/execution:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/ssca/plancreator:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/stage:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/stage/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/beans:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/evaluation:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/v1/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/evaluation:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/outcomes:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness/v1/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/beans:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/beans/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/beans:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/evaluation:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/v1/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/beans:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/event:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers/service/visitor:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/changeadvisor:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/changeadvisor/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/common/pipeline:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/constants:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/exception:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/output:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/execution/plugin:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/ssca:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/email/v1/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/executables:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/fme:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/http/v1/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/update:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/variables:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/beans:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/service:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/utils:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/importset:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/upload:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/telemetry/helpers:module",
    ],
)

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["src/test/**/*.java"]),
    resources = ["//pipeline-service/modules/orchestration-steps/src/test/resources:resource"],
    visibility = ["//pipeline-service:__subpackages__"],
    deps = [
        ":module",
        "//:lombok",
        "//440-connector-nextgen/src/main/java/io/harness/serializer/kryo:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps/workloadidentity:module",
        "//930-ng-core-clients/src/main/java/io/harness/user/remote:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/instancesync:module",
        "//960-persistence:supporter-test",
        "//960-persistence/src/main/java/io/harness/objectstore:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml:module",
        "//990-commons-test:module",
        "//clients/harnessid/src/main/java/io/harness/harnessid/client:module",
        "//clients/pipeline-service/pms-sdk:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/provider/impl:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/serializer/json:module",
        "@maven//:com_github_tomakehurst_wiremock_jre8_standalone",
        "@maven//:io_fabric8_fabric8_utils",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_inline",
        "@maven//:org_powermock_powermock_api_mockito2",
        "@maven//:org_powermock_powermock_core",
        "@maven//:org_powermock_powermock_module_junit4",
    ],
)

run_tests()

java_test(
    name = "OrchestrationStepsComponentTest",
    srcs = ["src/test/java/io/harness/OrchestrationStepsComponentTest.java"],
    resources = ["//pipeline-service/modules/orchestration-steps/src/test/resources:resource"],
    tags = ["component_test"],
    test_class = "io.harness.OrchestrationStepsComponentTest",
    visibility = ["//pipeline-service:__subpackages__"],
    deps = [
        ":module",
        ":tests",
        "//:lombok",
        "@maven//:com_github_tomakehurst_wiremock_jre8_standalone",
        "@maven//:io_fabric8_fabric8_utils",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_inline",
        "@maven//:org_powermock_powermock_api_mockito2",
        "@maven//:org_powermock_powermock_core",
        "@maven//:org_powermock_powermock_module_junit4",
    ],
)

# run static analysis macro for pmd/checkstyle/sonarqube checks
run_analysis(
    run_pmd = False,
)
