# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/rbac:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//930-ng-core-clients/src/main/java/io/harness/fme:module",
        "//930-ng-core-clients/src/main/java/io/harness/user/remote:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/v1:module",
        "//959-ng-persistence/src/main/java/io/harness/mongo/iterator/filter:module",
        "//959-ng-persistence/src/main/java/io/harness/mongo/iterator/provider:module",
        "//959-timeout-engine/src/main/java/io/harness/timeout:module",
        "//960-continuous-features/src/generated/java/io/harness/cf/openapi:module",
        "//960-continuous-features/src/main/java/io/harness/cf:module",
        "//960-continuous-features/src/main/java/io/harness/cf/openapi/model:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user:module",
        "//960-persistence/src/main/java/io/harness/iterator:module",
        "//960-persistence/src/main/java/io/harness/mongo/index:module",
        "//960-persistence/src/main/java/io/harness/mongo/iterator:module",
        "//960-persistence/src/main/java/io/harness/mongo/iterator/pojos:module",
        "//960-persistence/src/main/java/io/harness/ng:module",
        "//960-persistence/src/main/java/io/harness/persistence/api:module",
        "//970-api-services-beans/src/main/java/io/harness/logging:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/entitydetail:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//970-ng-commons/src/main/java/io/harness/yaml/core/timeout:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager:module",
        "//980-commons/src/main/java/io/harness/expression:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/cf:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/fme:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/executables:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/fme/enums:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/fme/exception:module",
        "//pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/constants:module",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_squareup_okhttp3_okhttp",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:io_github_resilience4j_resilience4j_core",
        "@maven//:javax_validation_validation_api",
        "@maven//:joda_time_joda_time",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
