# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/main/java/io/harness/ng/core/artifacts/resources/custom/script:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/buckets/resources/s3/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/acr/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/acr/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/artifactory/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/artifactory/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/custom:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/docker/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/docker/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/ecr/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/ecr/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/gcr/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/googleartifactregistry/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/googleartifactregistry/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/jenkins/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/jenkins/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/nexus/dtos:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/artifact/resources/nexus/service:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/service/steps/constants:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/evaluators:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/telemetry/helpers:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/bamboo:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/artifact/resources/bamboo/dtos:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/buckets/resources/s3:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/dtos:module",
        "//125-cd-nextgen/src/main/java/io/harness/cdng/k8s/resources/azure/service:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/customartifact:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/nexusartifact:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/visitor:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/beans:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/environment/services:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/entity:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/service/services/impl:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverride/beans:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/beans:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/serviceoverridev2/service:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/utils:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/accesscontrol:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitx:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/azure:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/source:module",
        "//953-yaml-commons/src/main/java/io/harness/plancreator/steps:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/fqn:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml/validation:module",
        "//953-yaml-commons/src/main/java/io/harness/template/yaml/ref:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/core/variables:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/utils:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/template:module",
        "//970-api-services-beans/src/main/java/software/wings/helpers/ext/jenkins:module",
        "//970-api-services-beans/src/main/java/software/wings/helpers/ext/nexus:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/beans/inputset:module",
        "//970-ng-commons/src/main/java/io/harness/common:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/beans:module",
        "//970-ng-commons/src/main/java/io/harness/plancreator/steps:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/data/algorithm:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/gitcaching:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote:module",
        "//clients/template-service/src/main/java/io/harness/template/remote:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset:module",
        "//platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit:module",
        "//template-service/contracts/src/main/java/io/harness/template/resources/beans:module",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_inject_guice",
        "@maven//:com_intellij_annotations",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
