# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//440-certificate-nextgen/src/main/java/io/harness/serializer/morphia:module",
        "//440-connector-nextgen/src/main/java/io/harness/serializer/morphia:module",
        "//874-orchestration-delay/src/main/java/io/harness/serializer:module",
        "//878-ng-common-utilities/src/main/java/io/harness/serializer:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/serializer/kryo:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/ambiance:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/facilitators/response:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/nodeexecution:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/orchestrationMap:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/outcomes:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/plannode:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/retryInfo:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/sdk:module",
        "//884-pms-commons/src/main/java/io/harness/serializer/spring/converters/steptype:module",
        "//890-sm-core/src/main/java/io/harness/serializer:module",
        "//890-sm-core/src/main/java/io/harness/serializer/morphia:module",
        "//920-delegate-agent-beans/src/main/java/io/harness/serializer:module",
        "//920-delegate-service-beans/src/main/java/io/harness/serializer/kryo:module",
        "//930-ng-license-manager/src/main/java/io/harness/serializer/kryo:module",
        "//930-ng-license-manager/src/main/java/io/harness/serializer/morphia:module",
        "//940-primary-version-manager/src/main/java/io/harness/serializer/morphia:module",
        "//940-secret-manager-client/src/main/java/io/harness/serializer/kryo:module",
        "//950-ng-core/src/main/java/io/harness/serializer/kryo:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/serializer/kryo:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/serializer:module",
        "//956-feature-flag-beans/src/main/java/io/harness/serializer:module",
        "//959-common-entities/src/main/java/io/harness/serializer/kryo:module",
        "//959-timeout-engine/src/main/java/io/harness/serializer/spring/converters/timeout/obtainment:module",
        "//980-commons/src/main/java/io/harness/morphia:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//oidc-core/src/main/java/io/harness/oidc/entities:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/serializer:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/serializer/spring/converters/stepparameters:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/kryo:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/morphia:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/morphia/converters:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/advisers/obtainment:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/advisers/response:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/advisers/type:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/consumerconfig:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/dependencyGraph:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/errorInfo:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/executableresponse:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/executionContext:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/executionmetadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/expansionhandler:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/facilitators/obtainment:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/facilitators/type:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/failureinfo:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/governancemetadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/graphlayout:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/interrupt:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/logging:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/pipelinechaining:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/principal:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/refobject:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/reftype:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/run:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/skip:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/stepoutcomeref:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/steps:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/sweepingoutput:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/template:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/triggers:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/serializer:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/serializer:module",
        "//template-service/service/src/main/java/io/harness/serializer/kryo:module",
        "//template-service/service/src/main/java/io/harness/serializer/morphia:module",
        "@maven//:com_google_guava_guava",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:org_springframework_spring_core",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
