# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/constants:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/entities:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/errorhandler:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/errorhandler/dtos:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/services/api:module",
        "//120-ng-manager/src/main/java/io/harness/repositories/ng/webhook/spring:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/ng:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/artifact/bean/yaml/harnessartifact:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/common/service:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/entity:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/metrics:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/gitxwebhooks/service/gitxwebhook:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/services:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/api:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/scm:module",
        "//950-ng-core/src/main/java/io/harness/ng/webhook:module",
        "//950-ng-core/src/main/java/io/harness/ng/webhook/services/api:module",
        "//952-scm-java-client/src/main/java/io/harness/beans:module",
        "//952-scm-java-client/src/main/java/io/harness/beans/gitsync:module",
        "//952-scm-java-client/src/main/java/io/harness/constants:module",
        "//952-scm-java-client/src/main/java/io/harness/exception:module",
        "//952-scm-java-client/src/main/java/io/harness/service:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/impl/redis:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//954-connector-beans/src/main/java/io/harness/connector:module",
        "//954-connector-beans/src/main/java/io/harness/connector/utils:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/intfc:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-ng-persistence/src/main/java/io/harness/mongo/iterator/filter:module",
        "//959-ng-persistence/src/main/java/io/harness/mongo/iterator/provider:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/har:module",
        "//960-persistence/src/main/java/io/harness/iterator:module",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//960-persistence/src/main/java/io/harness/mongo/iterator:module",
        "//960-persistence/src/main/java/io/harness/mongo/iterator/pojos:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/scope:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/runtime:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/manage:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/api:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
