# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/cd/beans/outcomes:module",
        "//878-ng-common-utilities/src/main/java/io/harness/cdng/instance/outcome:module",
        "//878-ng-common-utilities/src/main/java/io/harness/configFiles:module",
        "//878-ng-common-utilities/src/main/java/io/harness/executions/steps:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/utils:module",
        "//930-ng-core-clients/src/main/java/io/harness/filestore/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/organization/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/project/remote:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/expression:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/fqn/helpers:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/beans:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/expression/functors:module",
        "//980-commons/src/main/java/io/harness/network:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/data:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution/expression:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver/outputs:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/utils/execution:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/stages:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/approval/step/beans:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/shellscript:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/entities:module",
        "//pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/pms/plan/execution/beans:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/settings/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/blockExecutionMetadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/metadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/outcome:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/sweepingoutput:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/helpers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/intfc:module",
        "@maven//:com_google_guava_guava",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
