# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//874-orchestration-delay/src/main/java/io/harness/delay:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/logstreaming:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/engine/pms/data:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/interrupts:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/interrupts:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/exception:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/evaluator:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/exception:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/intfc:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/observers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/modifier/ambiance:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/callback/waitretry/v2:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/tasks:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail/service:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
