# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/execution/license:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/stages:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/dependencies:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/outcomes:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/enforcement:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/metadata:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/states:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/utils:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/validation:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/repositories:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/app/beans/entities:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/environment:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/outcomes:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/steps/stepinfo:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/config:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/buildstate:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage/vm/intfc:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/utils/ci:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/repositories:module",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/rbac:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps:module",
        "//878-ng-common-utilities/src/main/java/io/harness/steps/matrix:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/execution:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/outcomes:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/serializer:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/outcome:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/stepinfo:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/sweepingoutputs:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/buildIntelligence:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/cache:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/infrastrucutre:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/commonconstants:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/executable:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/metrics:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/metrics/helper:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/stepdetails:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/execution:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/repositories:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/runner/request/builder:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/runner/request/builder/constants:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/runner/request/helpers:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//900-runner-commons/src/main/java/io/harness/runnercommons/logging:module",
        "//910-delegate-service-driver/src/main/java/io/harness/beans:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//920-delegate-service-beans/src/main/proto/io/harness/delegate/task:920_schedule_task_service_beans_java_proto",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/dlite:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/runner:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/steps:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/vm/taskparams:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/helper:module",
        "//951-delegate-task-commons/src/main/java/io/harness/delegate/beans:module",
        "//951-delegate-task-commons/src/main/java/software/wings/beans:module",
        "//953-yaml-commons/src/main/java/io/harness/plancreator/execution:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/v1:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/core/variables:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/beans/summary/dto:module",
        "//960-persistence/src/main/java/io/harness/persistence:module",
        "//970-api-services-beans/src/main/java/io/harness/logging:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/entitydetail:module",
        "//970-ng-commons/src/main/java/io/harness/plancreator/steps:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//970-ng-commons/src/main/java/io/harness/yaml/core/timeout:module",
        "//980-commons/src/main/java/io/harness/data/encoding:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/tasks:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/pipeline-service/pms-sdk-core:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/api:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
