# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/dependencies:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/execution/license:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/stages:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/providers:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate/utils:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/integrationstage/secret:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/utils:module",
        "//332-hsa/commons/src/main/java/io/harness/hsa/client:module",
        "//332-ssca/ci/src/main/java/io/harness/ssca/execution:module",
        "//332-ssca/commons/src/main/java/io/harness/ssca/client:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/environment:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/executionargs:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/stages:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/steps/stepinfo:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/config:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/buildstate:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/execution/intfc:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage/ci:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage/k8s:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage/utils:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/utils/ci:module",
        "//878-ng-common-utilities/src/main/java/io/harness/common:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/environment:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/environment/pod/container:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/execution:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/quantity/unit:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/serializer:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/sweepingoutputs:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/cache:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/infrastrucutre:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/buildstate:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/commonconstants:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/utils:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/plugin/service:module",
        "//880-pipeline-cd-commons/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//930-delegate-tasks/src/main/java/io/harness/delegate/task/citasks/cik8handler/params:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/k8s:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//953-yaml-commons/src/main/java/io/harness/plancreator/execution:module",
        "//953-yaml-commons/src/main/java/io/harness/plancreator/strategy:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/extended/ci/codebase:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/extended/ci/container:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/utils:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//970-api-services-beans/src/main/java/io/harness/k8s/model:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/container/utils/yaml:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_inject_guice",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
