# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//332-ssca/cd/src/main/java/io/harness/ssca/cd/execution/filtercreator:module",
        "//332-ssca/cd/src/main/java/io/harness/ssca/cd/execution/variablecreator:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/plancreator/steps/pluginstep:module",
        "//884-pms-commons/src/main/java/io/harness/pms/utils:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/filters:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/group:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/inject/creator:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/filter/creation:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/filters:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/pipeline/variables:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/children:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/creators/pipeline:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/variables/helper:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/cf/pipeline:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/filters:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/approval/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/pipeline:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/dynamic:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/dynamic/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/barrier:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/barrier/unified:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/changeadvisor/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/email:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/email/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/http/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/internal/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/opa:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/pluginstep:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/steps/resourceconstraint:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/pms/sdk/core/pipeline/variables:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/ssca/plancreator:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/custom/unified:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/harness:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/unified:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/jira/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/approval/step/servicenow/unified:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/barriers:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/cf:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/eventlistener:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/fme:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/create:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/jira/update:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/pipelinestage:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/step:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/unified:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/policy/variables:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/resourcerestraint/unified:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/create:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/importset:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/servicenow/update:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/shellscript/v1:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/upload:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/upload/unified:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/steps/wait/unified:module",
        "//pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/steps:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinerollback:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/creator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/unified:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/plancreator:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
