# Copyright 2026 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//884-pms-commons/src/main/java/io/harness/pms/rbac:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//990-commons-test/src/main/java/io/harness:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//pipeline-service/contracts/openapi/v1:pipeline-server-spec-module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion:beans",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/service:module",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
    ],
)

run_tests("*Test.java")
