# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//867-polling-contracts/src/main/java/io/harness/dto:module",
        "//867-polling-contracts/src/main/java/io/harness/polling/client:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/rbac:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events/base:module",
        "//884-pms-commons/src/main/java/io/harness/pms/rbac:module",
        "//910-delegate-service-driver/src/main/java/io/harness/grpc:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//930-ng-core-clients/src/main/java/io/harness/connector:module",
        "//930-ng-core-clients/src/main/java/io/harness/serviceaccount/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/userng/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/utils:module",
        "//930-ng-core-clients/src/main/java/io/harness/webhook/remote:module",
        "//933-ci-commons/src/main/java/io/harness/secrets:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/services/api:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//950-ng-core/src/main/java/io/harness/ng/webhook:module",
        "//952-scm-java-client/src/main/java/io/harness/beans:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/fqn:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml/validation:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//954-connector-beans/src/main/java/io/harness/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/utils:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/api:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-api-services/src/main/java/io/harness/git:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user/remote/dto:module",
        "//960-persistence/src/main/java/io/harness/iterator:module",
        "//970-api-services-beans/src/main/java/io/harness/security/encryption:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/common:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/beans:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/dto:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//980-commons/src/main/java/io/harness/beans:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/network:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/api:module",
        "//clients/queue-service/java-client/src/main/java/io/harness/hsqs/client/model:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/config:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/catalog:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/entity/metadata/status:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/response:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/artifact:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/harnessartifactregistry/action:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/dto:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/buildtriggers/helpers:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/events:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/exceptions/yaml:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/instrumentation:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/mapper:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/service:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils/polling:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/validations/impl:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/validations/result:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/spring:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/execution:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers:module",
        "@maven//:com_cronutils_cron_utils",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_intellij_annotations",
        "@maven//:com_squareup_okhttp3_okhttp",
        "@maven//:com_squareup_retrofit2_retrofit",
        "@maven//:javax_cache_cache_api",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_mongodb_mongo_java_driver",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_core",
        "@maven//:org_springframework_spring_tx",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
