# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/dto:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/helper:module",
        "//884-pms-commons/src/main/java/io/harness/pms/gitsync:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/helpers:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans:module",
        "//953-git-sync-commons/src/main/java/io/harness/gitsync/common/helper:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/api:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//970-api-services-beans/src/main/java/io/harness/git/model:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/beans:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/interceptor:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/sdk:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/events:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/events/delete:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/mongo:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/response:module",
        "//pipeline-service/service/src/main/java/io/harness/utils:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:net_jodah_failsafe",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_tx",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
