# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/modules/ldap/src/main/java/io/harness/ldap/scheduler:module",
        "//120-ng-manager/src/main/java/io/harness/ng/code/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/consumer:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/manager:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/event/modulelicense:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/licenseusage/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/licenseusage/utils:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/manifests:module",
        "//120-ng-manager/src/main/java/io/harness/ng/runner/scheduledtask/response/artifactpolling:module",
        "//120-ng-manager/src/main/java/io/harness/ng/runner/scheduledtask/response/driftdetection:module",
        "//120-ng-manager/src/main/java/io/harness/ng/runner/scheduledtask/response/example:module",
        "//120-ng-manager/src/main/java/io/harness/ng/runner/scheduledtask/response/instancesync:module",
        "//122-ng-authentication-settings/src/main/java/io/harness/ng/authenticationsettings:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/invites/mapper:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/service:module",
        "//136-git-sync-manager/src/main/java/io/harness/gitsync/common/impl:module",
        "//440-connector-nextgen/src/main/java/io/harness/ng/core/event/manager:module",
        "//930-ng-core-clients/src/main/java/io/harness/user/remote:module",
        "//930-ng-license-manager/src/main/java/io/harness/credit/entities:module",
        "//930-ng-license-manager/src/main/java/io/harness/credit/services:module",
        "//940-feature-flag/src/main/java/io/harness/ff:module",
        "//950-ng-core/src/main/java/io/harness/ng/core/accountsetting/services:module",
        "//950-ng-core/src/main/java/io/harness/ng/core/licenseusage/entities:module",
        "//950-ng-core/src/main/java/io/harness/repositories/licenseusage:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user:module",
        "//960-ng-license-beans/src/main/java/io/harness/credit/beans/credits:module",
        "//960-ng-license-beans/src/main/java/io/harness/credit/utils:module",
        "//960-persistence/src/main/java/io/harness/beans:module",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//960-persistence/src/main/java/io/harness/timescaledb:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/code:module",
        "//970-ng-commons/src/main/java/io/harness/entities:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/common/beans:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/utils:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api:module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:io_dropwizard_dropwizard_lifecycle",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_tx",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
