# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis_for_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//120-ng-manager/src/main/java/io/harness/pms/expressions/functors:module",
        "//120-ng-manager/src/main/java/io/harness/pms/expressions/utils:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/configfile:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/expressions:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/featureFlag:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/harness:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/services:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/cdng/artifact/outcome:module",
        "//878-ng-common-utilities/src/main/java/io/harness/cdng/instance/outcome:module",
        "//878-ng-common-utilities/src/main/java/io/harness/configFiles:module",
        "//878-ng-common-utilities/src/main/java/io/harness/executions/steps:module",
        "//884-pms-commons/src/main/java/io/harness/pms/plan/execution:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//954-connector-beans/src/main/java/io/harness/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/scm/github:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/utils:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/encryption:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//990-commons-test/src/main/java/io/harness:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_intellij_annotations",
        "@maven//:junit_junit",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
    ],
)

run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

run_tests("*Test.java")
