# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/fqn:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/fqn/helpers:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/helpers:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/merger/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml/validation:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//959-timeout-engine/src/main/java/io/harness/timeout:module",
        "//970-ng-commons/src/main/java/io/harness/common:module",
        "//970-ng-commons/src/main/java/io/serializer/utils:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/jackson:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/tasks:module",
        "//980-commons/src/main/java/io/harness/waiter:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/adviser/proceedwithdefault:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/plan:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/executioninput:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:net_jodah_failsafe",
        "@maven//:org_springframework_spring_core",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
