// Copyright 2025 Harness Inc. All rights reserved.
// Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
// that can be found in the licenses directory at the root of this repository, also available at
// https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

syntax = "proto3";

package io.harness.pms.contracts.template;

option java_multiple_files = true;

message TemplateReferenceSummary {
  string templateRef = 1;
  string versionLabel = 2;
  string gitBranch = 3;

  // v1 template metadata
  string uses = 4;
  string iconName = 5;
  string description = 6;
  string name = 7;
}
