# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/service/beans:module",
        "//315-sto-manager/contracts/src/main/java/io/harness/sto:module",
        "//315-sto-manager/contracts/src/main/java/io/harness/sto/creator/variables:module",
        "//315-sto-manager/contracts/src/main/java/io/harness/sto/plan/creator/step:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/execution/license:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/executionconfig/api:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/yamlschema/api:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/beans/entities:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/creator/variables:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/execution:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/filter:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/stage/V3:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/step:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/steps:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plancreator:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plancreator/V1:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/states:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/repositories:module",
        "//332-hsa/ci/src/main/java/io/harness/hsa:module",
        "//332-hsa/ci/src/main/java/io/harness/hsa/execution/creator/filter:module",
        "//332-hsa/ci/src/main/java/io/harness/hsa/execution/creator/plan:module",
        "//332-hsa/ci/src/main/java/io/harness/hsa/execution/creator/variable:module",
        "//332-ssca/ci/src/main/java/io/harness/ssca:module",
        "//332-ssca/ci/src/main/java/io/harness/ssca/execution/creator/filter:module",
        "//332-ssca/ci/src/main/java/io/harness/ssca/execution/creator/plan:module",
        "//332-ssca/ci/src/main/java/io/harness/ssca/execution/creator/variable:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/app/beans/entities:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/stages/parameters:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/steps:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/beans/steps/stepinfo:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/cd/beans/moduleinfo:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/buildstate:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/integrationstage:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/utils:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/repositories:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/execution:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/serializer:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/steps/outcome:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/sweepingoutputs:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/sweepingoutputs/stepartifacts:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/beans/yaml/extended/infrastrucutre:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/billing/service:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/commonconstants:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/plancreator:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/repositories:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ssca/execution/orchestration/outcome:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/steps/plugin:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/utils:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/constants:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/sdk/core/steps/io/v1:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer/recaster:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/extended/ci/codebase:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/extended/ci/codebase/spec:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-api-services/src/main/java/io/harness/git:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/beans/summary/dto:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception:module",
        "//980-commons/src/main/java/io/harness/utils:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/core/execution:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/beans:module",
        "//idp-service/src/main/java/io/harness/idp/common:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:io_harness_platform_data_contracts_event_models",
        "@maven//:io_harness_platform_data_contracts_shared_models",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
