# Copyright 2026 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/rbac:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//pipeline-service/contracts/openapi/v1:pipeline-server-spec-module",  # Generated spec models
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/annotations:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion:beans",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/mapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/service:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_inject_guice",
        "@maven//:io_dropwizard_metrics_metrics_annotation",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
    ],
)
