# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis_for_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/utils:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/dto:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/entities:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/mapper:module",
        "//120-ng-manager/src/main/java/io/harness/ng/opa/entities/apiKey:module",
        "//120-ng-manager/src/main/java/io/harness/ng/opa/entities/token:module",
        "//120-ng-manager/src/main/java/io/harness/ng/serviceaccounts/service/api:module",
        "//120-ng-manager/src/main/java/io/harness/repositories/ng/core/spring:module",
        "//120-ng-manager/src/test/java/io/harness/base:tests",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/entities:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/entities:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/service:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/utils:module",
        "//400-rest-commons/src/main/java/io/harness/delegate/beans:module",
        "//420-delegate-service/src/main/java/io/harness/delegate/filter:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/helper:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/services:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//890-sm-core/src/main/java/io/harness/encryption:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/api:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/dao:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/models:module",
        "//890-sm-core/src/main/java/io/harness/secrets:module",
        "//890-sm-core/src/main/java/software/wings/service/impl/security:module",
        "//890-sm-delegate/src/main/java/io/harness/ng/core/entities:module",
        "//910-delegate-service-driver/src/main/java/io/harness/grpc:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service:module",
        "//920-delegate-service-beans/src/main/java/io/harness/exception:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//930-delegate-tasks/src/main/java/io/harness/beans:module",
        "//930-delegate-tasks/src/main/java/io/harness/delegate/utils:module",
        "//930-ng-core-clients/src/main/java/io/harness/entitysetupusageclient:module",
        "//931-encryption-service/src/java/io/harness/encryptors/clients:module",
        "//931-encryption-service/src/java/io/harness/exception:module",
        "//931-secret-providers/src/java/io/harness/beans:module",
        "//931-secret-providers/src/java/io/harness/mappers:module",
        "//931-secret-providers/src/java/software/wings/beans:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core/remote:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/config:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/configupdate:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/remote:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/services:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/ci/pod:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/secrets:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/ng/core:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/secretmanagerclient:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/events:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//954-connector-beans/src/main/java/io/harness/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/customsecretmanager:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/utils:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//955-delegate-beans/src/main/java/io/harness/delegate/beans:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/dto:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/service:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/api:module",
        "//955-setup-usage-sdk/src/main/java/io/harness/ng/core/entitysetupusage/service:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-file-service-commons/src/main/java/io/harness/file:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/account:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user/remote/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/usergroups/filter:module",
        "//960-persistence/src/main/java/io/harness/beans:module",
        "//960-persistence/src/main/java/io/harness/utils:module",
        "//965-ng-filter/src/main/java/io/harness/token:module",
        "//970-api-services-beans/src/main/java/io/harness/encryptors:module",
        "//970-api-services-beans/src/main/java/io/harness/filter:module",
        "//970-api-services-beans/src/main/java/io/harness/security/encryption:module",
        "//970-api-services-beans/src/main/java/software/wings/settings:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/code:module",
        "//970-ng-commons/src/main/java/io/harness/connector:module",
        "//970-ng-commons/src/main/java/io/harness/encryption:module",
        "//970-ng-commons/src/main/java/io/harness/ng/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/common/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/dto:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/entitysetupusage/dto:module",
        "//970-ng-commons/src/main/java/io/harness/secrets:module",
        "//970-ng-commons/src/main/java/io/harness/serviceaccount:module",
        "//970-ng-commons/src/main/java/io/harness/utils/fullyqualifiedidentifier:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/beans:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager/exceptionhandler:module",
        "//980-commons/src/main/java/io/harness/rest:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/threading:module",
        "//980-commons/src/main/java/software/wings:module",
        "//980-commons/src/main/java/software/wings/beans:module",
        "//990-commons-test/src/main/java/io/harness:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/resourcegroups/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/roleassignments/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/roles/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/scopes:module",
        "//clients/access-control/admin-client/src/main/java/io/harness/accesscontrol:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//clients/template-service/src/main/java/io/harness/template/remote:module",
        "//favorites/src/main/java/io/harness/favorites/services:module",
        "//ng-settings/contracts/src/main/java/io/harness/ngsettings:module",
        "//ng-settings/contracts/src/main/java/io/harness/ngsettings/dto:module",
        "@maven//:com_amazonaws_aws_java_sdk_core",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_intellij_annotations",
        "@maven//:com_squareup_retrofit2_retrofit",
        "@maven//:io_dropwizard_dropwizard_util",
        "@maven//:io_github_benas_random_beans",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:junit_junit",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_security_spring_security_crypto",
        "@maven//:org_springframework_spring_tx",
    ],
)

run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

run_tests("*Test.java")
