# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/main/java/io/harness/ng/core/invites:module",
        "//120-ng-manager/src/main/java/io/harness/repositories/invites/spring:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol/user:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/events:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/invites/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/invites/entities:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/invites/mapper:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/invites/utils:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/service:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//930-ng-core-clients/src/main/java/io/harness/invites/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/user/remote:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/services:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/usage:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/beans:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/beans/metadata:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/constants:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/exceptions:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/api:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/account:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/invites:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/invites/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user/remote/dto:module",
        "//960-persistence/src/main/java/io/harness/mongo:module",
        "//960-persistence/src/main/java/io/harness/utils:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/ng/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/common/beans:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-telemetry-beans/src/main/java/io/harness/telemetry:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/utils:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/notification/src/main/java/io/harness/notification/channeldetails:module",
        "//clients/notification/src/main/java/io/harness/notification/notificationclient:module",
        "//ng-settings/contracts/src/main/java/io/harness/ngsettings:module",
        "//ng-settings/contracts/src/main/java/io/harness/ngsettings/dto:module",
        "//ng-settings/src/main/java/io/harness/ngsettings/services:module",
        "@maven//:com_auth0_java_jwt",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_j256_two_factor_auth_two_factor_auth",
        "@maven//:net_jodah_failsafe",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_apache_httpcomponents_httpclient",
        "@maven//:org_apache_httpcomponents_httpcore",
        "@maven//:org_mongodb_mongo_java_driver",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_tx",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
