# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/common/utils:module",
        "//878-ng-common-utilities/src/main/java/io/harness/engine/governance:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/helper:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events/base:module",
        "//884-pms-commons/src/main/java/io/harness/pms/merger/helpers:module",
        "//884-pms-commons/src/main/java/io/harness/pms/rbac:module",
        "//952-scm-java-client/src/main/java/io/harness/beans:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/beans:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/interceptor:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/pipeline-service/pms-client/src/main/java/io/harness/pipeline/remote:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/plan/execution:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/config:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/dto:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/git:module",
        "//pipeline-service/modules/ng-triggers/contracts/src/main/java/io/harness/ngtriggers/beans/source/webhook/v2/spec:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/dto:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/entity:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/beans/scm:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/expressions:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/helpers:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/ngtriggers/utils:module",
        "//pipeline-service/modules/ng-triggers/src/main/java/io/harness/repositories/custom/impl:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/engine/executions/retry:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/evaluator:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/inputset:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/intfc:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
