# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis_for_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//960-persistence/src/main/java/io/harness/objectstore:module",
        "//990-commons-test/src/main/java/io/harness:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/accountoverrides:module",
        "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/dataretention/config:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/cleanup:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/dataretention/service:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/search/service:module",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_springframework_spring_test",
    ],
)

run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

run_tests("*Test.java")
