# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/engine/governance:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/dto:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/helper:module",
        "//878-ng-common-utilities/src/main/java/io/harness/gitx:module",
        "//878-ng-common-utilities/src/main/java/io/harness/opa/gitx:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/rbac:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/interceptor:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm/beans:module",
        "//953-yaml-commons/src/main/java/io/harness/allowedvalues:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/variables:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/core:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/template:module",
        "//960-persistence/src/main/java/io/harness/utils:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml/schema:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml/validator:module",
        "//970-api-services-beans/src/main/java/io/harness/git/model:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/gitsync/sdk:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/dto:module",
        "//970-ng-commons/src/main/java/io/harness/yaml/validator/beans:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/exception/ngexception/beans/yamlschema:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol/publicaccess:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol/publicaccess/dto:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol/publicaccess/utils:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/goverance:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/inputfile:module",
        "//pipeline-service/contracts/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/notification/bean:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/plancreator/steps/internal:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/template:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/template/stage:module",
        "//pipeline-service/modules/orchestration-steps/contracts/src/main/java/io/harness/steps/upload:module",
        "//pipeline-service/modules/orchestration-visualization/contracts/src/main/java/io/harness/beans:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/accountoverrides:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/accountoverrides/beans:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/accountoverrides:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/annotations:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/dataretention/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/helpers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/opa/gitx/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/annotations:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/branchsequence:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/enforcement:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/response:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/beans:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/variables:module",
        "//pipeline-service/service/src/main/java/io/harness/utils:module",
        "@maven//:com_google_inject_guice",
        "@maven//:com_squareup_retrofit2_retrofit",
        "@maven//:commons_io_commons_io",
        "@maven//:io_swagger_core_v3_swagger_annotations",
        "@maven//:io_swagger_swagger_annotations",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_json_json",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
