# Copyright 2026 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/main/java/io/harness/ng/core/sfexecution:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/sfexecution/entity:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/sfexecution/mappers:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/sfexecution/services:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/sfexecution/services/impl:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/ng/core/utils:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//950-ng-core/src/main/java/io/harness/ng/core/utils:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/mapper:module",
        "//970-ng-commons/src/main/java/io/harness/security/annotations:module",
        "//970-ng-commons/src/main/java/io/harness/utils:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_springframework_data_spring_data_commons",
        "@maven//:org_springframework_data_spring_data_mongodb",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
