# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_binary")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis")

shared_dependencies = [
    "//955-delegate-beans:module",
    "//959-timeout-engine/src/main/java/io/harness/serializer/spring/converters/timeout/obtainment:module",
    "//pipeline-service/contracts/src/main/java/io/harness/pms/notificationbodyresolution:module",
    "//pipeline-service/modules/orchestration/contracts:module",
    "//pipeline-service/modules/orchestration-beans:module",
    "//platform-service/modules/audit-service/contracts/src/main/java/io/harness/audit:module",
    "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/monitoring:module",
    "//pipeline-service/modules/pms-contracts:module",
    "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/retention:module",
    "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/search/entity/beans:module",
    "//pipeline-service/modules/retention/src/main/java/io/harness/dataretention/service:module",
    "//pipeline-service/modules/retention/src/main/java/io/harness/serializer:module",
    "//874-orchestration-delay:module",
    "//878-ng-common-utilities:module",
    "//884-pms-commons:module",
    "//890-sm-core/src/main/java/io/harness/encryption:module",
    "//910-delegate-service-driver:module",
    "//oidc-core/src/main/java/io/harness/oidc/entities:module",
    "//930-delegate-tasks:module",
    "//930-ng-core-clients:module",
    "//953-yaml-commons/src/main/java/io/harness/notification:module",
    "//953-yaml-commons/src/main/java/io/harness/pms/yaml/processor:module",
    "//955-account-mgmt:module",
    "//950-opa-client:module",
    "//950-wait-engine:module",
    "//956-feature-flag-beans:module",
    "//960-ng-license-beans:module",
    "//960-persistence/src/main/java/io/harness/mongo/iterator/provider:module",
    "//960-persistence/src/main/java/io/harness/objectstore:module",
    "//970-ng-commons:module",
    "@maven_redisson//:com_esotericsoftware_kryo",
    "@maven//:com_fasterxml_jackson_core_jackson_annotations",
    "@maven//:com_github_luben_zstd_jni",
    "@maven//:com_google_code_findbugs_annotations",
    "@maven//:com_google_guava_guava",
    "@maven//:com_google_inject_guice",
    "@maven//:javax_validation_validation_api",
    "@maven//:org_apache_commons_commons_lang3",
    "@maven//:org_hibernate_validator_hibernate_validator",
    "@maven//:org_mongodb_mongodb_driver_core",
    "@maven//:dev_morphia_morphia_core",
    "@maven//:org_slf4j_slf4j_api",
    "@maven//:org_springframework_data_spring_data_commons",
    "@maven//:org_springframework_data_spring_data_mongodb",
    "@maven//:org_springframework_spring_context",
    "@maven//:org_springframework_spring_core",
    "//:lombok",
]

java_library(
    name = "module",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = ["//pipeline-service:__subpackages__"],
    exports = [
        "//pipeline-service/modules/orchestration/src/main/java/io/harness:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/overrides:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/settings/response:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/settings/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/settings/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/concurrency:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/config:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/events:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution/consumers/flowgovernor:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executioncheck:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/blockExecutionMetadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/concurrency:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/config:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/exception:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/helper:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/stage:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/evaluator:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/type:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/metadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/provider:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/provider/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/beans:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/dto:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/expressiontracker:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/async:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/chain:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/child:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/chilidren:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/secondary:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/sync:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/task:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/waitStep:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/callback:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/exception:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/factory:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/intfc:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/intfc:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/manager:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/statusupdate:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/observers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/observers/beans:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/factory:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/handlers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/audits/events:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/commons/events:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/outcome:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/outcome/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/sweepingoutput:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/sweepingoutput/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/modifier/ambiance:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/factory:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/helper:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/helper/intfc:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/identity:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/node:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plan:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/plannode:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/callback/resume:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/callback/resumeall:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/callback/waitretry:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/callback/waitretry/v2:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/publisher/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/start:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/tasks:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/progress:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/progress/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/secrets:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/timeouts:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/accountoverrides:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/accountoverrides/beans:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/eventlog:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/event:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/event/handlers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/consumers/sdk/response:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/helpers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/metrics:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/metrics/observers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/pms:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/blockexecution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/executioninput:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/expressionusages:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/interrupt:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/nodeentity:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/notificationEventLog:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/orchestrationEventLog:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/plan:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/planExecutionJson:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/planexecution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/stageexecution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/stepDetail:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/stepexecution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/waitstep:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/kryo:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/morphia:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/morphia/converters:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/advisers/obtainment:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/advisers/response:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/advisers/type:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/consumerconfig:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/errorInfo:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/executableresponse:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/executionContext:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/executionmetadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/expansionhandler:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/facilitators/obtainment:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/facilitators/type:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/failureinfo:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/governancemetadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/graphlayout:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/interrupt:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/logging:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/pipelinechaining:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/principal:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/refobject:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/reftype:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/run:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/skip:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/stepoutcomeref:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/steps:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/sweepingoutput:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/serializer/spring/converters/triggers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/waiter:module",
    ],
)

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["src/test/**/*.java"]),
    resources = ["//pipeline-service/modules/orchestration/src/test/resources:resource"],
    visibility = ["//pipeline-service:__subpackages__"],
    deps = shared_dependencies + [
        ":module",
        "//440-connector-nextgen/src/main/java/io/harness/serializer/kryo:module",
        "//960-persistence:supporter-test",
        "//990-commons-test:module",
        "//clients/pipeline-service/pms-sdk:module",
        "@maven//:com_github_ben_manes_caffeine_caffeine",
        "@maven//:commons_codec_commons_codec",
        "@maven//:commons_logging_commons_logging",
        "@maven//:junit_junit",
        "@maven//:org_apache_commons_commons_jexl3",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_awaitility_awaitility",
        "@maven//:org_jooq_joor",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_inline",
        "@maven//:org_powermock_powermock_api_mockito2",
        "@maven//:org_powermock_powermock_module_junit4",
        "@maven//:org_reflections_reflections",
        "@maven_redisson//:org_redisson_redisson",
    ],
)

run_tests()

java_test(
    name = "OrchestrationComponentTest",
    srcs = ["src/test/java/io/harness/OrchestrationComponentTest.java"],
    resources = ["//pipeline-service/modules/orchestration/src/test/resources:resource"],
    tags = ["component_test"],
    test_class = "io.harness.OrchestrationComponentTest",
    visibility = ["//pipeline-service:__subpackages__"],
    deps = shared_dependencies + [
        ":module",
        ":tests",
        "@maven//:commons_codec_commons_codec",
        "@maven//:commons_logging_commons_logging",
        "@maven//:junit_junit",
        "@maven//:org_apache_commons_commons_jexl3",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_awaitility_awaitility",
        "@maven//:org_jooq_joor",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_inline",
        "@maven//:org_powermock_powermock_api_mockito2",
        "@maven//:org_powermock_powermock_module_junit4",
        "@maven//:org_reflections_reflections",
    ],
)

# run static analysis macro for pmd/checkstyle/sonarqube checks
run_analysis(
    run_pmd = False,
)
