# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis_for_tests")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/polling:module",
        "//120-ng-manager/src/main/java/io/harness/ng/webhook/resources:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/polling/bean:module",
        "//125-cd-nextgen/src/main/java/io/harness/polling/bean:module",
        "//125-cd-nextgen/src/main/java/io/harness/polling/bean/artifact:module",
        "//125-cd-nextgen/src/main/java/io/harness/polling/service/intfc:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml:module",
        "//127-cd-nextgen-entities/src/main/java/io/harness/cdng/manifest/yaml/storeConfig:module",
        "//867-polling-contracts/src/main/java/io/harness/dto:module",
        "//867-polling-contracts/src/main/java/io/harness/polling/artifact:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/beans/polling:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/artifactory:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/azure:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/docker:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/ecr:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/gar:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/gcr:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/githubpackages:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/googlecloudstorage:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/nexus:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/response:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/delegate/task/artifacts/source:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//960-persistence/src/main/java/io/harness/lock/noop:module",
        "//970-api-services-beans/src/main/java/io/harness/gitpolling/github:module",
        "//970-api-services-beans/src/main/java/io/harness/k8s/model:module",
        "//970-api-services-beans/src/main/java/io/harness/logging:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//990-commons-test/src/main/java/io/harness:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//990-commons-test/src/main/java/io/harness/rule:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//ng-settings/contracts/src/main/java/io/harness/ngsettings:module",
        "//ng-settings/contracts/src/main/java/io/harness/ngsettings/dto:module",
        "@maven//:com_google_inject_guice",
        "@maven//:com_squareup_retrofit2_retrofit",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:junit_junit",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
    ],
)

run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

run_tests("*Test.java")
