id: ID_PLACEHOLDER
name: ID_PLACEHOLDER

inputs:
  extractionScript:
    type: string
    description: Extraction script for custom remote store
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.extractionScript}}
  filePath:
    type: string
    description: File path for custom remote store
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.filePath}}
  delegateSelectors:
    type: list
    description: Delegate selectors for custom remote task
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.delegateSelectors}}
  samTemplateFile:
    type: string
    description: SAM template file path
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.samTemplateFile}}


run:
  type: run
  container:
    image: alpine
  script: |-
    ${{inputs.extractionScript}}

