id: ID_PLACEHOLDER
name: ID_PLACEHOLDER

inputs:
  extractionScript:
    type: string
    description: Extraction script for custom remote store
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.extractionScript}}
  paths:
    type: list
    description: File path for custom remote store
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.filePath}}
  delegateSelectors:
    type: list
    description: Delegate selectors for custom remote task
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.delegateSelectors}}
  chartName:
    type: string
    description: Helm chart name
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.chartName}}
  chartVersion:
    type: string
    description: Helm chart version
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.chartVersion}}
  helmVersion:
    type: string
    description: Helm version
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.helmVersion}}
  valuesPaths:
    type: list
    description: Paths to values YAML files
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.valuesPaths}}
  skipResourceVersioning:
    type: boolean
    description: Skip resource versioning
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.skipResourceVersioning}}
  enableDeclarativeRollback:
    type: boolean
    description: Enable declarative rollback
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.enableDeclarativeRollback}}
  commandFlags:
    type: list
    description: Helm command flags
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.commandFlags}}
  subChartPath:
    type: string
    description: Sub-chart path
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.subChartPath}}
  fetchHelmChartMetadata:
    type: boolean
    description: Fetch Helm chart metadata
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.fetchHelmChartMetadata}}
  optionalValuesYaml:
    type: boolean
    description: Optional values YAML
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.optionalValuesYaml}}
  flags:
    type: string
    description: Command flags
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.commandFlags}}


run:
  type: run
  container:
    image: alpine
  script: |-
    [ ! -d "ID_PLACEHOLDER" ] && mkdir -p ID_PLACEHOLDER
    cd ID_PLACEHOLDER
    ${{inputs.extractionScript}}

