---
id: ID_PLACEHOLDER
name: ID_PLACEHOLDER
run:
  type: run
  container:
    image: harnessdev/acr-artifact-metadata:0.0.1
    connector: account.harnessImage
  env:
    PLUGIN_ARTIFACT_ID: ${{serviceOutput.manifests.ID_PLACEHOLDER.id}}
    PLUGIN_ARTIFACT_NAME: ${{serviceOutput.manifests.ID_PLACEHOLDER.id}}
    PLUGIN_ARTIFACT_SUBSCRIPTION_ID: ${{serviceOutput.manifests.ID_PLACEHOLDER.store.subscriptionId}}
    PLUGIN_ARTIFACT_REGISTRY_NAME: ${{serviceOutput.manifests.ID_PLACEHOLDER.store.registry}}
    PLUGIN_ARTIFACT_CHART_PATH: ${{serviceOutput.manifests.ID_PLACEHOLDER.store.path}}
    PLUGIN_ARTIFACT_CHART_NAME: ${{serviceOutput.manifests.ID_PLACEHOLDER.chartName}}
    PLUGIN_ARTIFACT_CHART_VERSION: ${{serviceOutput.manifests.ID_PLACEHOLDER.chartVersion}}
    PLUGIN_ARTIFACT_FORMAT: helm
    PLUGIN_DOWNLOAD_HELM_ARTIFACT: true
    PLUGIN_DOWNLOAD_ARTIFACT: true
    PLUGIN_AZURE_NAME: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).name}}
    PLUGIN_AZURE_CLIENT_ID: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).clientId}}
    PLUGIN_AZURE_TENANT_ID: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).tenantId}}
    PLUGIN_AZURE_ENV: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).envType}}
    PLUGIN_AZURE_SECRET: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).clientSecret}}
    PLUGIN_AZURE_CERTIFICATE_DATA: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).clientCertificate}}
    PLUGIN_AZURE_OIDC_TOKEN: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).oidcToken}}
    PLUGIN_AZURE_AUDIENCE: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).audience}}