---
id: ID_PLACEHOLDER
name: ID_PLACEHOLDER
run:
  type: run
  container:
    image: harnessdev/gar-artifact-metadata:0.0.1
    connector: account.harnessImage
  env:
    PLUGIN_ARTIFACT_ID: ${{serviceOutput.manifests.ID_PLACEHOLDER.id}}
    PLUGIN_ARTIFACT_NAME: ${{serviceOutput.manifests.ID_PLACEHOLDER.id}}
    PLUGIN_ARTIFACT_REPOSITORY_TYPE: helm
    PLUGIN_DOWNLOAD_HELM_ARTIFACT: true
    PLUGIN_DOWNLOAD_ARTIFACT: true
    PLUGIN_ARTIFACT_PROJECT_ID: ${{serviceOutput.manifests.ID_PLACEHOLDER.store.project}}
    PLUGIN_ARTIFACT_REGION: ${{serviceOutput.manifests.ID_PLACEHOLDER.store.region}}
    PLUGIN_ARTIFACT_REPOSITORY_NAME: ${{serviceOutput.manifests.ID_PLACEHOLDER.store.repository}}
    PLUGIN_ARTIFACT_CHART_NAME: ${{serviceOutput.manifests.ID_PLACEHOLDER.chartName}}
    PLUGIN_ARTIFACT_CHART_VERSION: ${{serviceOutput.manifests.ID_PLACEHOLDER.chartVersion}}
    PLUGIN_GCP_NAME: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).name}}
    PLUGIN_GCP_SERVICE_ACCOUNT_KEY: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).jsonKey}}
    PLUGIN_POOL_ID: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).workloadPoolId}}
    PLUGIN_PROVIDER_ID: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).providerId}}
    PLUGIN_PROJECT_NUMBER: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).gcpProjectId}}
    PLUGIN_SERVICE_ACCOUNT_EMAIL: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).serviceAccountEmail}}
    PLUGIN_OIDC_TOKEN_ID: ${{connectorInputs.get(${{serviceOutput.manifests.ID_PLACEHOLDER.store.connector}}).oidcToken}}
