id: ID_PLACEHOLDER
name: ID_PLACEHOLDER

inputs:
  extractionScript:
    type: string
    description: Extraction script for custom remote store
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.extractionScript}}
  filePath:
    type: string
    description: File path for custom remote store
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.filePath}}
  delegateSelectors:
    type: list
    description: Delegate selectors for custom remote task
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.store.spec.delegateSelectors}}
  optionalValuesYaml:
    type: boolean
    description: Optional values YAML
    default: ${{ngService.spec.manifests.ID_PLACEHOLDER.manifest.spec.optionalValuesYaml}}


run:
  type: run
  container:
    image: alpine
  script: |-
    [ ! -d "ID_PLACEHOLDER" ] && mkdir -p ID_PLACEHOLDER
    cd ID_PLACEHOLDER
    ${{inputs.extractionScript}}

