# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    resources = [
        "//980-commons/src/main/resources-filtered:resource",
        "//clients/pipeline-service/pms-sdk/src/main/resources:resource",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//310-iacm-manager/app/src/main/java/io/harness/app:module",
        "//323-sto-utilities/src/main/java/io/harness/sto/beans/entities:module",
        "//323-sto-utilities/src/main/java/io/harness/stoserviceclient:module",
        "//332-ci-manager/app/src/main/java/io/harness/ci/api/aitestautomation:module",
        "//332-ci-manager/app/src/main/java/io/harness/ci/migration:module",
        "//332-ci-manager/contracts/src/main/java/io/harness/cimanager/execution/license:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/app/impl:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/app/intfc:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/cache:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/cd/service:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/core/ci/dashboard:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/dashboard:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/buildstate:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/enforcement:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/event:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/artifactDetails:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/execution/queue:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/license/impl:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator/filter:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plugin:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/registrars:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/serializer:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/states/V1/cd:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/validation:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/licensing:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/plugin:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/savings:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/serializer:module",
        "//332-ci-manager/service/src/main/java/io/harness/ci/telemetry:module",
        "//332-hsa/commons/src/main/java/io/harness/hsa/beans:module",
        "//332-iacm-common/src/main/java/io/harness/beans/entities:module",
        "//332-iacm-common/src/main/java/io/harness/iacmserviceclient:module",
        "//332-idp/src/main/java/io/harness/steps/beans/stepnode:module",
        "//332-ssca/commons/src/main/java/io/harness/fulcio/beans:module",
        "//332-ssca/commons/src/main/java/io/harness/ssca/beans/entities:module",
        "//332-ssca/commons/src/main/java/io/harness/ssca/client:module",
        "//420-delegate-service/src/main/java/io/harness/serializer:module",
        "//440-connector-nextgen/src/main/java/io/harness/serializer:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/app/beans/entities:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/beans/entities:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/cacheserviceclient:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/config:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/logserviceclient:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/tiserviceclient:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/utils:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ng/core/utils:module",
        "//878-ng-common-utilities/src/main/java/io/harness:module",
        "//878-ng-common-utilities/src/main/java/io/harness/logstreaming:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/listener:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/ff/impl:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/permission:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/traceableagenttoken:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/ci/traceableagenttoken/impl:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events/base:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/events:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/persistance/testing:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/scm:module",
        "//900-git-sync-sdk/src/main/java/io/harness/gitsync/sdk:module",
        "//910-delegate-service-driver/src/main/java/io/harness/grpc:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service:module",
        "//910-delegate-service-driver/src/main/java/io/harness/service/impl:module",
        "//920-delegate-service-beans/src/main/java/io/harness/delegate/beans:module",
        "//920-delegate-service-beans/src/main/proto:920_delegate_service_beans_java_proto",
        "//930-ng-core-clients/src/main/java/io/harness/code:module",
        "//930-ng-core-clients/src/main/java/io/harness/connector:module",
        "//930-ng-core-clients/src/main/java/io/harness/creditcard:module",
        "//930-ng-core-clients/src/main/java/io/harness/entitysetupusageclient:module",
        "//930-ng-core-clients/src/main/java/io/harness/envgroup:module",
        "//930-ng-core-clients/src/main/java/io/harness/environment:module",
        "//930-ng-core-clients/src/main/java/io/harness/filestore:module",
        "//930-ng-core-clients/src/main/java/io/harness/infrastructure:module",
        "//930-ng-core-clients/src/main/java/io/harness/privateconnectivity:module",
        "//930-ng-core-clients/src/main/java/io/harness/project:module",
        "//930-ng-core-clients/src/main/java/io/harness/runner/cgi:module",
        "//930-ng-core-clients/src/main/java/io/harness/runner/plugin:module",
        "//930-ng-core-clients/src/main/java/io/harness/secrets:module",
        "//930-ng-core-clients/src/main/java/io/harness/tunnel:module",
        "//930-ng-core-clients/src/main/java/io/harness/unified/depoloymentfreeze:module",
        "//930-ng-core-clients/src/main/java/io/harness/unified/service:module",
        "//930-ng-core-clients/src/main/java/io/harness/user:module",
        "//933-ci-commons/src/main/java/io/harness/secrets:module",
        "//940-feature-flag/src/main/java/io/harness/ff:module",
        "//940-primary-version-manager/src/main/java/io/harness/app:module",
        "//940-primary-version-manager/src/main/java/io/harness/controller:module",
        "//940-primary-version-manager/src/main/java/io/harness/resource:module",
        "//940-primary-version-manager/src/main/java/io/harness/serializer:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/servicedependencies:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/services:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/usage:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/constants:module",
        "//945-license-usage-sdk/src/main/java/io/harness/licensing/usage/interfaces:module",
        "//950-log-client/src/main/java/io/harness/logstreaming:module",
        "//950-opa-client/src/main/java/io/harness/opaclient:module",
        "//950-telemetry/src/main/java/io/harness/telemetry:module",
        "//950-telemetry/src/main/java/io/harness/telemetry/segment:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//950-wait-engine/src/main/java/io/harness/waiter/nrcsp:module",
        "//952-scm-java-client/src/main/java/io/harness:module",
        "//952-scm-java-client/src/main/java/io/harness/impl:module",
        "//952-scm-java-client/src/main/java/io/harness/service:module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/impl/noop:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/impl/redis:module",
        "//953-events-api/src/main/java/io/harness/ng/core/event:module",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/serializer:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/core:module",
        "//955-account-mgmt/src/main/java/io/harness/account:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox:module",
        "//955-outbox-sdk/src/main/java/io/harness/outbox/module",
        "//958-migration-sdk/src/main/java/io/harness/migration/ng:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//960-api-services/src/main/java/io/harness/aitestautomation/client:module",
        "//960-api-services/src/main/java/io/harness/aitestautomation/service:module",
        "//960-api-services/src/main/java/io/harness/aws:module",
        "//960-api-services/src/main/java/io/harness/cistatus/service:module",
        "//960-api-services/src/main/java/io/harness/cistatus/service/azurerepo:module",
        "//960-api-services/src/main/java/io/harness/cistatus/service/bitbucket:module",
        "//960-api-services/src/main/java/io/harness/cistatus/service/gitlab:module",
        "//960-api-services/src/main/java/io/harness/gcp/client:module",
        "//960-api-services/src/main/java/io/harness/gcp/impl:module",
        "//960-continuous-features/src/main/java/io/harness/cf:module",
        "//960-continuous-features/src/main/java/io/harness/ff:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/exceptionmappers:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/remote:module",
        "//960-persistence/src/main/java/io/harness/cache:module",
        "//960-persistence/src/main/java/io/harness/iterator:module",
        "//960-persistence/src/main/java/io/harness/lock:module",
        "//960-persistence/src/main/java/io/harness/mongo:module",
        "//960-persistence/src/main/java/io/harness/mongo/index:module",
        "//960-persistence/src/main/java/io/harness/ng:module",
        "//960-persistence/src/main/java/io/harness/persistence:module",
        "//960-persistence/src/main/java/io/harness/persistence/api:module",
        "//960-persistence/src/main/java/io/harness/persistence/store:module",
        "//960-persistence/src/main/java/io/harness/queue:module",
        "//960-persistence/src/main/java/io/harness/redis:module",
        "//960-persistence/src/main/java/io/harness/serializer:module",
        "//960-persistence/src/main/java/io/harness/timescaledb:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml:module",
        "//960-yaml-sdk/src/main/java/io/harness/yaml/schema/beans:module",
        "//965-ng-filter/src/main/java/io/harness/security:module",
        "//965-ng-filter/src/main/java/io/harness/token:module",
        "//965-ng-filter/src/main/java/io/harness/token/remote:module",
        "//970-grpc/src/main/java/io/harness/grpc/client:module",
        "//970-grpc/src/main/java/io/harness/grpc/interceptor:module",
        "//970-grpc/src/main/java/io/harness/grpc/server:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/filter:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/jobs:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/modules:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/security/annotations:module",
        "//970-ng-commons/src/main/java/io/serializer/mapper:module",
        "//970-telemetry-beans/src/main/java/io/harness/telemetry:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/concurrent:module",
        "//980-commons/src/main/java/io/harness/configuration:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/dropwizard/bundles/configured:module",
        "//980-commons/src/main/java/io/harness/dropwizard/bundles/swagger:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/govern:module",
        "//980-commons/src/main/java/io/harness/health:module",
        "//980-commons/src/main/java/io/harness/logging:module",
        "//980-commons/src/main/java/io/harness/maintenance:module",
        "//980-commons/src/main/java/io/harness/manage:module",
        "//980-commons/src/main/java/io/harness/metrics:module",
        "//980-commons/src/main/java/io/harness/morphia:module",
        "//980-commons/src/main/java/io/harness/packages:module",
        "//980-commons/src/main/java/io/harness/reflection:module",
        "//980-commons/src/main/java/io/harness/secret:module",
        "//980-commons/src/main/java/io/harness/security/mesh:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/threading:module",
        "//980-commons/src/main/java/io/harness/version:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/access-control/sdk/src/main/java/io/harness:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/go-convert/src/main/java/io/harness/goconvert:module",
        "//clients/harness-fulcio/src/main/java/io/harness/fulcio:module",
        "//clients/harnessid/src/main/java/io/harness/harnessid/client:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//clients/pipeline-service/pms-sdk-core:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/configuration:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/facilitators:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/interrupts:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/advise:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/resume:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/node/start:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/orchestrationevent:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/plan:module",
        "//clients/pipeline-service/pms-sdk/src/main/java/io/harness/pms/sdk/execution/events/progress:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/serializer/json:module",
        "//srm-service/modules/cv-nextgen-service/contracts/api/src/main/java/io/harness/cvng/client:module",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml",
        "@maven//:com_github_rutledgepaulv_q_builders",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:io_dropwizard_dropwizard_configuration",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:io_dropwizard_dropwizard_jackson",
        "@maven//:io_dropwizard_dropwizard_jersey",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:io_swagger_core_v3_swagger_annotations",
        "@maven//:io_swagger_core_v3_swagger_integration",
        "@maven//:io_swagger_core_v3_swagger_jaxrs2",
        "@maven//:io_swagger_core_v3_swagger_models",
        "@maven//:jakarta_servlet_jakarta_servlet_api",
        "@maven//:jakarta_ws_rs_jakarta_ws_rs_api",
        "@maven//:javax_cache_cache_api",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:net_sourceforge_argparse4j_argparse4j",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_glassfish_jersey_core_jersey_server",
        "@maven//:org_hibernate_validator_hibernate_validator",
        "@maven//:org_redisson_redisson",
        "@maven//:org_reflections_reflections",
        "@maven//:org_slf4j_log4j_over_slf4j",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_core",
        "@maven//:org_springframework_spring_tx",
        "@maven//:ru_vyarus_guice_validator",
    ],
)

java_binary(
    name = "CIManagerApplication",
    main_class = "io.harness.app.CIManagerApplication",
    visibility = ["//visibility:public"],
    runtime_deps = [":module"],
    deps = [],
)
