# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//120-ng-manager/src/main/java/io/harness/ng/config:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/api/impl:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/beans:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/deployable/resources:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/dto:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/entities:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/environment/resources:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/infrastructure/resource:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/licensedmodules/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/licenseusage/services:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/manifests:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/service/resources:module",
        "//120-ng-manager/src/main/java/io/harness/ng/core/sfcomparisonpair/resources:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol/scopes:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/accesscontrol/usergroup:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/api:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/dto:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/entities:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/user/remote/dto:module",
        "//123-ng-core-user/src/main/java/io/harness/ng/core/utils:module",
        "//125-cd-nextgen/modules/common/core/src/main/java/io/harness/cdng/envGroup/resource:module",
        "//400-rest-commons/src/main/java/software/wings/beans/sso:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/accesscontrol:module",
        "//440-connector-nextgen/src/main/java/io/harness/connector/services:module",
        "//440-secret-management-service/src/main/java/io/harness/ng/core/api/impl:module",
        "//440-secret-management-service/src/main/java/io/harness/ng/core/remote:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/rbac:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/pms/utils:module",
        "//890-sm-core/src/main/java/io/harness/ng/core/api:module",
        "//890-sm-core/src/main/java/software/wings/service/impl/security:module",
        "//930-ng-license-manager/src/main/java/io/harness/credit/entities:module",
        "//930-ng-license-manager/src/main/java/io/harness/credit/services:module",
        "//930-ng-license-manager/src/main/java/io/harness/licensing/services:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core/api:module",
        "//940-secret-manager-client/src/main/java/io/harness/ng/core/dto:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto:module",
        "//940-secret-manager-client/src/main/java/io/harness/secretmanagerclient/dto/config:module",
        "//942-enforcement-sdk/src/main/java/io/harness/enforcement/client/annotation:module",
        "//943-enforcement-beans/src/main/java/io/harness/enforcement/constants:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/ng/core:module",
        "//950-delegate-tasks-beans/src/main/java/io/harness/secretmanagerclient:module",
        "//950-ng-authentication-service/src/main/java/software/wings/beans/sso:module",
        "//950-ng-core/src/main/java/io/harness/ng/validator/dto:module",
        "//950-ng-core/src/main/java/io/harness/ng/validator/service/api:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/entities:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/remote:module",
        "//950-ng-project-n-orgs/src/main/java/io/harness/ng/core/services:module",
        "//954-connector-beans/src/main/java/io/harness/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/pdcconnector:module",
        "//955-account-mgmt/src/main/java/io/harness/account/accesscontrol:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/user/remote/dto:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/usergroups/filter:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/beans/modules:module",
        "//960-persistence/src/main/java/io/harness/utils:module",
        "//970-api-services-beans/src/main/java/io/harness/security/encryption:module",
        "//970-ng-commons/src/main/java/io/harness:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/beans/scope:module",
        "//970-ng-commons/src/main/java/io/harness/constants:module",
        "//970-ng-commons/src/main/java/io/harness/encryption:module",
        "//970-ng-commons/src/main/java/io/harness/filestore:module",
        "//970-ng-commons/src/main/java/io/harness/ng/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/common/beans:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/dto:module",
        "//970-ng-commons/src/main/java/io/harness/ng/core/utils:module",
        "//970-ng-commons/src/main/java/io/harness/secrets:module",
        "//970-ng-commons/src/main/java/io/harness/security/annotations:module",
        "//970-ng-commons/src/main/java/io/harness/utils:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/annotations:module",
        "//980-commons/src/main/java/io/harness/beans:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/data/validator:module",
        "//980-commons/src/main/java/io/harness/encryption:module",
        "//980-commons/src/main/java/io/harness/eraro:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/filesystem:module",
        "//980-commons/src/main/java/io/harness/health:module",
        "//980-commons/src/main/java/io/harness/maintenance:module",
        "//980-commons/src/main/java/io/harness/rest:module",
        "//980-commons/src/main/java/io/harness/security/annotations:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/commons/exceptions:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/scopes:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//favorites/contracts/src/main/java/io/harness/favorites:module",
        "//favorites/src/main/java/io/harness/favorites/entities:module",
        "//favorites/src/main/java/io/harness/favorites/services:module",
        "//license-manager/src/main/java/io/harness/services:module",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_squareup_retrofit2_retrofit",
        "@maven//:com_typesafe_config",
        "@maven//:commons_collections_commons_collections",
        "@maven//:io_dropwizard_dropwizard_jersey",
        "@maven//:io_dropwizard_metrics_metrics_annotation",
        "@maven//:io_dropwizard_metrics_metrics_healthchecks",
        "@maven//:io_swagger_core_v3_swagger_annotations",
        "@maven//:io_swagger_swagger_annotations",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_glassfish_jersey_media_jersey_media_multipart",
        "@maven//:org_hibernate_validator_hibernate_validator",
        "@maven//:org_springframework_data_spring_data_commons",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
