# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "tests",
    testonly = True,
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//990-commons-test/src/main/java/io/harness:module",
        "//990-commons-test/src/main/java/io/harness/category/element:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//pipeline-service/modules/orchestration-steps/src/main/java/io/harness/plancreator/stages/dynamic:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/dynamic:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/repositories/dynamic:module",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_slf4j_jcl_over_slf4j",
        "@maven//:org_slf4j_jul_to_slf4j",
        "@maven//:org_slf4j_log4j_over_slf4j",
        "@maven//:org_slf4j_slf4j_api",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
    test_only = True,
)

run_tests("*Test.java")
