# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//874-orchestration-delay/src/main/java/io/harness/delay:module",
        "//878-ng-common-utilities/src/main/java/io/harness/engine:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/expression:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events:module",
        "//950-wait-engine/src/main/java/io/harness/waiter:module",
        "//950-wait-engine/src/main/java/io/harness/waiter/module",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/impl/noop:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/impl/redis:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//955-account-mgmt/src/main/java/io/harness/account:module",
        "//960-ng-license-beans/src/main/java/io/harness/licensing/remote:module",
        "//960-persistence/src/main/java/io/harness/cache:module",
        "//960-persistence/src/main/java/io/harness/queue:module",
        "//960-persistence/src/main/java/io/harness/redis:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception/exceptionmanager:module",
        "//980-commons/src/main/java/io/harness/govern:module",
        "//980-commons/src/main/java/io/harness/logging/autolog:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//980-commons/src/main/java/io/harness/testing:module",
        "//980-commons/src/main/java/io/harness/threading:module",
        "//980-commons/src/main/java/io/harness/version:module",
        "//980-commons/src/main/java/io/harness/waiter:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/waiter:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/waiter:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/interrupts:module",
        "//pipeline-service/modules/orchestration/contracts/src/main/java/io/harness/abort:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/settings/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/account/settings/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/config:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/blockExecutionMetadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/concurrency/counter:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/concurrency/planqueue:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/concurrency/queue:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/concurrency/rebuild:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/gitmetadata/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/gitmetadata/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/detection:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/node/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/stage:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/step:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/provider:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/usages/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/facilitation/facilitator/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/handlers/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/helpers/intfc:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/interrupts/service/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/advise/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/expression/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/outcome:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/outcome/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/sweepingoutput:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/sweepingoutput/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/helper:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/execution/strategy/helper/intfc:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/resume/publisher/impl:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/tasks:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/progress/publisher:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/event:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/dynamic:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/pms:module",
        "@maven//:com_esotericsoftware_kryo",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:javax_cache_cache_api",
        "@maven//:org_redisson_redisson",
        "@maven//:org_reflections_reflections",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
