# Copyright 2023 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("//:tools/bazel/harness.bzl", "java_library")

java_library(
    name = "module",
    srcs = glob(["**/*.java"]),
    resources = [],
    visibility = [
        "//332-ci-manager/service/src/main/java/io/harness/ci/execution/plan/creator:__pkg__",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/idp/utils:__subpackages__",
        "//879-pipeline-ci-commons/src/main/java/io/harness/utils:__pkg__",
        "//idp-service:__subpackages__",
    ],
    deps = [
        "//:lombok",
        "//878-ng-common-utilities/src/main/java/io/harness/gitaware/helper:module",
        "//878-ng-common-utilities/src/main/java/io/harness/ngmanager:module",
        "//930-ng-core-clients/src/main/java/io/harness/organization/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/project/remote:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services:module",
        "//955-account-mgmt/src/main/java/io/harness/account/services/impl:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//959-ng-persistence/src/main/java/io/harness/springdata:module",
        "//960-api-services/src/main/java/io/harness/retry:module",
        "//960-ng-core-beans/src/main/java/io/harness/ng/core/dto:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils:module",
        "//970-ng-commons/src/main/java/io/harness/utils/yaml:module",
        "//970-ng-commons/src/main/java/io/serializer/jackson:module",
        "//980-commons/src/main/java/io/harness/beans/user:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//980-commons/src/main/java/io/harness/serializer:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/acl/api:module",
        "//access-control/contracts/api/src/main/java/io/harness/accesscontrol/principals:module",
        "//clients/notification/src/main/java/io/harness/notification/channeldetails:module",
        "//clients/notification/src/main/java/io/harness/notification/notificationclient:module",
        "//idp-service/contracts/openapi/v1:idp-service-server-spec-module",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_guava",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jdk8",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
        "@maven//:com_google_cloud_google_cloud_storage",
        "@maven//:com_google_code_gson_gson",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_squareup_okhttp3_okhttp",
        "@maven//:commons_io_commons_io",
        "@maven//:commons_lang_commons_lang",
        "@maven//:io_github_resilience4j_resilience4j_retry",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:net_sf_json_lib_json_lib",
        "@maven//:org_apache_commons_commons_lang3",
        "@maven//:org_json_json",
        "@maven//:org_yaml_snakeyaml",
        "@maven//:software_amazon_awssdk_auth",
        "@maven//:software_amazon_awssdk_regions",
        "@maven//:software_amazon_awssdk_s3",
        "@maven//:software_amazon_awssdk_sdk_core",
    ],
)
