# Copyright 2025 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//323-sto-utilities/src/main/java/io/harness/qwietserviceclient:module",
        "//323-sto-utilities/src/main/java/io/harness/sto/beans/entities:module",
        "//323-sto-utilities/src/main/java/io/harness/stoserviceclient:module",
        "//877-pipeline-ci-cd-commons/src/java/io/harness/ci/execution/buildstate:module",
        "//878-ng-common-utilities/src/main/java/io/harness/pms/rbac:module",
        "//878-ng-common-utilities/src/main/java/io/harness/utils:module",
        "//879-pipeline-ci-commons/src/main/java/io/harness/runner/request/helpers/infra:module",
        "//880-pipeline-cd-commons/src/main/java/io/harness/utils:module",
        "//884-pms-commons/src/main/java/io/harness/expression:module",
        "//884-pms-commons/src/main/java/io/harness/pms/events/base:module",
        "//884-pms-commons/src/main/java/io/harness/pms/execution/utils:module",
        "//890-sm-core/src/main/java/io/harness/encryption:module",
        "//930-ng-core-clients/src/main/java/io/harness/connector:module",
        "//930-ng-core-clients/src/main/java/io/harness/secrets/remote:module",
        "//930-ng-core-clients/src/main/java/io/harness/usergroups:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/protohelper:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//953-yaml-commons/src/main/java/io/harness/pms/yaml:module",
        "//953-yaml-commons/src/main/java/io/harness/yaml/utils:module",
        "//954-connector-beans/src/main/java/io/harness/connector:module",
        "//954-connector-beans/src/main/java/io/harness/delegate/beans/connector/utils:module",
        "//956-feature-flag-beans/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/beans:module",
        "//970-ng-commons/src/main/java/io/harness/common:module",
        "//970-ng-commons/src/main/java/io/harness/metrics/service/api:module",
        "//970-ng-commons/src/main/java/io/harness/pms/yaml:module",
        "//970-ng-commons/src/main/java/io/harness/remote/client:module",
        "//970-ng-commons/src/main/java/io/harness/utils/identifierref:module",
        "//980-commons/src/main/java/io/harness/authorization:module",
        "//980-commons/src/main/java/io/harness/data/structure:module",
        "//980-commons/src/main/java/io/harness/exception:module",
        "//980-commons/src/main/java/io/harness/expression:module",
        "//980-commons/src/main/java/io/harness/expression/celcustomfunctor:module",
        "//980-commons/src/main/java/io/harness/expression/common:module",
        "//980-commons/src/main/java/io/harness/expression/functors:module",
        "//980-commons/src/main/java/io/harness/observer:module",
        "//980-commons/src/main/java/io/harness/security:module",
        "//980-commons/src/main/java/io/harness/security/dto:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//clients/access-control/sdk/src/main/java/io/harness/accesscontrol:module",
        "//clients/ngsettings/src/main/java/io/harness/ngsettings/client/remote:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/engine/pms/data:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/plancreator/strategy:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/execution:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/plan/creation/yaml:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/sdk/core/resolver:module",
        "//clients/pipeline-service/pms-sdk-core/src/main/java/io/harness/pms/security:module",
        "//ng-settings/contracts/src/main/java/io/harness/ngsettings:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/contracts/src/main/java/io/harness/plan:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/execution:module",
        "//pipeline-service/modules/orchestration-beans/src/main/java/io/harness/pms/execution/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/execution:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/executions/plan/service:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/constants:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/functors/type:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/metadata:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/expressions/secretUtils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/observers:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/outcome:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/pms/data/sweepingoutput:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/engine/utils:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/execution/expansion:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/graph/stepDetail/service:module",
        "//platform-service/modules/notification-service/src/main/java/io/harness/notification/remote:module",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:org_apache_commons_commons_lang3",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
