# Copyright 2022 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_binary")
load("//:tools/bazel/GenTestRules.bzl", "run_tests")
load("//:tools/bazel/macros.bzl", "run_analysis", "run_analysis_for_tests")

java_binary(
    name = "module",
    data = ["//:resource"],
    main_class = "io.harness.PipelineServiceApplication",
    resources = [
        "//970-ng-commons/src/main/resources:resource",
        "//clients/pipeline-service/pms-sdk/src/main/resources:resource",
        "//pipeline-service/service/src/main/resources:resource",
    ],
    visibility = [
        "//110-change-data-capture:__subpackages__",
        "//pipeline-service:__subpackages__",
    ],
    runtime_deps = [
        "//878-ng-common-utilities/src/main/java/io/harness/opa/gitx:module",
        "//955-filters-sdk/src/main/java/io/harness/filter/resource:module",
        "//pipeline-service/service/src/main/java/io/harness:module",
        "//pipeline-service/service/src/main/java/io/harness/config:module",
        "//pipeline-service/service/src/main/java/io/harness/enforcement:module",
        "//pipeline-service/service/src/main/java/io/harness/grpc/server:module",
        "//pipeline-service/service/src/main/java/io/harness/metrics:module",
        "//pipeline-service/service/src/main/java/io/harness/monitoring:module",
        "//pipeline-service/service/src/main/java/io/harness/notify:module",
        "//pipeline-service/service/src/main/java/io/harness/pipeline/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/aisre/resource:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/custom:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/jira:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/notification/stagemetadata:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/notification/stagemetadata/summary:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/notification/summary:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/approval/servicenow:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/barriers/beans:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/barriers/mapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/barriers/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/barriers/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion:beans",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/mapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/conversion/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/dashboard:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/dashboard/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/dataretention:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/entitycrud:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/filter:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/handlers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/overviewLandingPage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/pollingevent:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/triggerwebhookevent:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/event/webhookevent:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/events:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/events/delete:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/exception:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/expressions:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/expressions/functors:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/filter/creation:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/filter/creation/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/filter/utils:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/governance:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/health:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/helpers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset/gitsync:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset/gitsync/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/inputset/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/instrumentaion:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/instrumentaion/constants:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/instrumentaion/handler:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/jira:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/migration:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputs/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputs/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputs/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/api/utils:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/beans/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/exceptions:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/helpers/validate:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/observers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/handler:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/inputset/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/ngpipeline/overlayinputset/beans:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/instrumentation:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/handlers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/notification/orchestration/observers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/opa:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/opa/gitx/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/opa/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/outbox:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/outbox/autoLog:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/api/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/filters:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/gitsync/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/governance/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/labels:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/mappers/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/metadata:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/observer:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/observer/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/references:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/filter:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/references/runnable:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/resource:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/enforcement:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/response:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/approval:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/cache:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/exception:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/featureflag:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/getter:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/service/yamlschema/pipelinestage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/setupusage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/beans:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/handler:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/async/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/validation/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipeline/yaml:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinerollback:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/creator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/outcome:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/output:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/plancreator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/pipelinestage/v1/plancreator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation/info:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation/lookup:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation/lookup/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/creation/validator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/beans/dto:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/data/service/expressions:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/data/service/outcome:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/data/service/outputs:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/dryrun/semantic:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/dryrun/semantic/rules:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/handlers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/mapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/resource:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/execution/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plan/utils:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/plugin:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/preflight/entity:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/preflight/handler:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/preflight/mapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/preflight/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/preflight/service/intfc:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/rbac/validator:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/resources:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/resourceconstraints/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/schema:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/sdk:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/sdk/helper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/sdk/service/execution:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/servicenow:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/steps/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/tags:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/template:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/template/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/template/utils:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/api:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/build/eventmapper:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/scheduled:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/helpers:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/service:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/triggers/webhook/service/impl:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/variables:module",
        "//pipeline-service/service/src/main/java/io/harness/pms/wait:module",
        "//pipeline-service/service/src/main/java/io/harness/registrars:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/conversion:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/inputset:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/pipeline:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/pipeline/validation/async:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/preflight:module",
        "//pipeline-service/service/src/main/java/io/harness/repositories/sdk:module",
        "//pipeline-service/service/src/main/java/io/harness/serializer:module",
        "//pipeline-service/service/src/main/java/io/harness/serializer/jackson:module",
        "//pipeline-service/service/src/main/java/io/harness/serializer/jackson/json:module",
        "//pipeline-service/service/src/main/java/io/harness/serializer/kryo:module",
        "//pipeline-service/service/src/main/java/io/harness/serializer/morphia:module",
        "//pipeline-service/service/src/main/java/io/harness/utils:module",
        "//pipeline-service/service/src/main/java/io/harness/yaml/individualschema:module",
        "//pipeline-service/service/src/main/resources",
        "@maven//:ch_qos_logback_logback_access",
        "@maven//:ch_qos_logback_logback_classic",
        "@maven//:ch_qos_logback_logback_core",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_guava",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jdk8",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
        "@maven//:com_fasterxml_jackson_jaxrs_jackson_jaxrs_yaml_provider",
        "@maven//:com_google_code_findbugs_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:dev_morphia_morphia_core",
        "@maven//:io_dropwizard_dropwizard_configuration",
        "@maven//:io_dropwizard_dropwizard_core",
        "@maven//:io_dropwizard_dropwizard_jersey",
        "@maven//:io_dropwizard_dropwizard_jetty",
        "@maven//:io_dropwizard_dropwizard_logging",
        "@maven//:io_dropwizard_dropwizard_request_logging",
        "@maven//:io_dropwizard_metrics_metrics_core",
        "@maven//:io_netty_netty_all",
        "@maven//:io_opencensus_opencensus_api",
        "@maven//:io_opencensus_opencensus_contrib_http_util",
        "@maven//:io_opencensus_opencensus_impl",
        "@maven//:io_perfmark_perfmark_api",
        "@maven//:io_swagger_core_v3_swagger_annotations",
        "@maven//:io_swagger_core_v3_swagger_core",
        "@maven//:io_swagger_core_v3_swagger_integration",
        "@maven//:io_swagger_core_v3_swagger_jaxrs2",
        "@maven//:io_swagger_core_v3_swagger_jaxrs2_servlet_initializer_v2",
        "@maven//:io_swagger_core_v3_swagger_models",
        "@maven//:io_swagger_swagger_annotations",
        "@maven//:javax_servlet_javax_servlet_api",
        "@maven//:javax_validation_validation_api",
        "@maven//:javax_ws_rs_javax_ws_rs_api",
        "@maven//:net_jodah_failsafe",
        "@maven//:org_codehaus_janino_janino",
        "@maven//:org_eclipse_jetty_jetty_servlets",
        "@maven//:org_glassfish_jersey_core_jersey_server",
        "@maven//:org_glassfish_jersey_media_jersey_media_multipart",
        "@maven//:org_jooq_jooq",
        "@maven//:org_jooq_joor",
        "@maven//:org_modelmapper_modelmapper",
        "@maven//:org_postgresql_postgresql",
        "@maven//:org_reflections_reflections",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:org_springframework_data_spring_data_mongodb",
        "@maven//:org_springframework_spring_context",
        "@maven_redisson//:com_esotericsoftware_kryo",
    ],
)

# To know more about this configuration refer https://harness.atlassian.net/wiki/spaces/BT/pages/21681340453/BUILD.bazel+Files
run_analysis_for_tests(
    checkstyle_srcs = glob(["*"]),
)

# run static analysis macro for pmd/checkstyle/sonarqube checks
run_analysis(
    run_checkstyle = False,
    run_pmd = False,
)
