pipeline:
  name: __PIPELINE_NAME__
  identifier: __PIPELINE_IDENTIFIER__
  projectIdentifier: __PROJECT_IDENTIFIER__
  orgIdentifier: __ORG_IDENTIFIER__
  tags: {}
  stages:
    - stage:
        name: Salesforce Quick Deploy
        identifier: salesforce_quick_deploy
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: Salesforce Quick Deploy
                  identifier: salesforce_quick_deploy_sg
                  steps:
                    - step:
                        type: SalesforceQuickDeploy
                        name: SalesforceQuickDeploy
                        identifier: SalesforceQuickDeploy
                        spec:
                          connectorRef: account.harnessImage
                          image: <+input>
                          validatedDeployRequestId: <+input>
                        timeout: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                      namespace: <+input>
            rollbackSteps: []
          environment:
            environmentRef: salesforce_runtime
            deployToAll: false
            infrastructureDefinitions:
              - identifier: salesforce_runtime
                inputs:
                  identifier: salesforce_runtime
                  type: Salesforce
                  spec:
                    connectorRef: <+input>
          serviceDependencies: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
