pipeline:
  name: __PIPELINE_NAME__
  identifier: __PIPELINE_IDENTIFIER__
  projectIdentifier: __PROJECT_IDENTIFIER__
  orgIdentifier: __ORG_IDENTIFIER__
  tags: {}
  stages:
    - stage:
        name: Salesforce Evaluate Diff
        identifier: salesforce_evaluate_diff
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: Salesforce Evaluate Diff
                  identifier: salesforce_evaluate_diff_sg
                  steps:
                    - step:
                        type: SalesforceDownloadDeployables
                        name: SalesforceDownloadDeployables
                        identifier: SalesforceDownloadDeployables
                        spec:
                          connectorRef: account.harnessImage
                          image: <+input>
                          source1Type: <+input>
                          source2Type: <+input>
                          source1Ref: <+input>
                          source2Ref: <+input>
                          metadataTypes: <+input>
                    - step:
                        type: SalesforceEvaluateDiff
                        name: SalesforceEvaluateDiff
                        identifier: SalesforceEvaluateDiff
                        spec:
                          connectorRef: account.harnessImage
                          image: <+input>
                          diffOutputInline: true
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                      namespace: <+input>
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
