# Copyright 2024 Harness Inc. All rights reserved.
# Use of this source code is governed by the PolyForm Free Trial 1.0.0 license
# that can be found in the licenses directory at the root of this repository, also available at
# https://polyformproject.org/wp-content/uploads/2020/05/PolyForm-Free-Trial-1.0.0.txt.

load("@rules_java//java:defs.bzl", "java_library")
load("//:tools/bazel/macros.bzl", "run_analysis_per_module")

java_library(
    name = "module",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//:lombok",
        "//953-events-api/src/main/java/io/harness/eventsframework:module",
        "//953-events-api/src/main/java/io/harness/eventsframework/api:module",
        "//953-events-api/src/main/proto:953_events_api_java_proto",
        "//960-persistence/src/main/java/io/harness/lock/interfaces:module",
        "//960-persistence/src/main/java/io/harness/objectstore:module",
        "//980-commons/src/main/java/io/harness/maintenance:module",
        "//999-annotations/src/main/java/io/harness/annotations/dev:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/dataretention:module",
        "//pipeline-service/modules/orchestration/src/main/java/io/harness/entity/accountoverrides:module",
        "//pipeline-service/modules/pms-contracts/src/main/java/io/harness/pms/accountoverrides:module",
        "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/dataretention/config:module",
        "//pipeline-service/modules/retention/contracts/src/main/java/io/harness/dataretention/entity/beans:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/dataretention/service:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/logger:module",
        "//pipeline-service/modules/retention/src/main/java/io/harness/search/service:module",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_inject_guice",
        "@maven//:io_dropwizard_dropwizard_lifecycle",
        "@maven//:javax_annotation_javax_annotation_api",
    ],
)

run_analysis_per_module(
    checkstyle_srcs = glob(["*"]),
    pmd_srcs = glob(["*"]),
    sonarqube_srcs = glob(["*"]),
)
